import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getUserFromHeaders } from "@/lib/auth";
import { nextOrderNumber } from "@/lib/inventory/order-number";

// ─── POST /api/inventory/ai-decisions/execute ───────────────────────────
// Executes AI decisions: creates real draft POs or transfers in the DB.
//
// Body: { action: "purchase_order" | "transfer" | "all_pos" | "all_transfers", data: {...} }

export async function POST(req: NextRequest) {
  const caller = await getUserFromHeaders(req.headers);
  if (!caller) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await req.json();
  const { action, data } = body;

  try {
    // ─── Create a single Purchase Order ─────────────────────────────
    if (action === "purchase_order") {
      const { outletId, supplierId, items } = data as {
        outletId: string;
        supplierId: string;
        items: { productId: string; productPackageId: string | null; quantity: number; unitPrice: number }[];
      };

      const outlet = await prisma.outlet.findUniqueOrThrow({ where: { id: outletId }, select: { code: true } });
      const orderNumber = await nextOrderNumber(outlet.code);

      const totalAmount = items.reduce((s, i) => s + i.quantity * i.unitPrice, 0);

      const order = await prisma.order.create({
        data: {
          orderNumber,
          orderType: "PURCHASE_ORDER",
          outletId,
          supplierId,
          status: "DRAFT",
          totalAmount,
          notes: "Auto-generated by AI reorder engine",
          createdById: caller.id,
          items: {
            create: items.map((i) => ({
              productId: i.productId,
              productPackageId: i.productPackageId || null,
              quantity: i.quantity,
              unitPrice: i.unitPrice,
              totalPrice: i.quantity * i.unitPrice,
            })),
          },
        },
        select: { id: true, orderNumber: true, totalAmount: true },
      });

      return NextResponse.json({ created: [order] }, { status: 201 });
    }

    // ─── Create multiple POs at once ────────────────────────────────
    if (action === "all_pos") {
      const { purchaseOrders } = data as {
        purchaseOrders: {
          outletId: string;
          supplierId: string;
          items: { productId: string; productPackageId: string | null; quantity: number; unitPrice: number }[];
        }[];
      };

      const created = [];
      for (const po of purchaseOrders) {
        const outlet = await prisma.outlet.findUniqueOrThrow({ where: { id: po.outletId }, select: { code: true } });
        const orderNumber = await nextOrderNumber(outlet.code);
        const totalAmount = po.items.reduce((s, i) => s + i.quantity * i.unitPrice, 0);

        const order = await prisma.order.create({
          data: {
            orderNumber,
            orderType: "PURCHASE_ORDER",
            outletId: po.outletId,
            supplierId: po.supplierId,
            status: "DRAFT",
            totalAmount,
            notes: "Auto-generated by AI reorder engine",
            createdById: caller.id,
            items: {
              create: po.items.map((i) => ({
                productId: i.productId,
                productPackageId: i.productPackageId || null,
                quantity: i.quantity,
                unitPrice: i.unitPrice,
                totalPrice: i.quantity * i.unitPrice,
              })),
            },
          },
          select: { id: true, orderNumber: true, totalAmount: true },
        });
        created.push(order);
      }

      return NextResponse.json({ created }, { status: 201 });
    }

    // ─── Create a single Transfer ───────────────────────────────────
    if (action === "transfer") {
      const { fromOutletId, toOutletId, items } = data as {
        fromOutletId: string;
        toOutletId: string;
        items: { productId: string; productPackageId?: string; quantity: number }[];
      };

      const transfer = await prisma.stockTransfer.create({
        data: {
          fromOutletId,
          toOutletId,
          status: "DRAFT",
          transferredById: caller.id,
          notes: "Auto-generated by AI inventory balancer",
          items: {
            create: items.map((i) => ({
              productId: i.productId,
              productPackageId: i.productPackageId || null,
              quantity: i.quantity,
            })),
          },
        },
        select: { id: true, fromOutlet: { select: { name: true } }, toOutlet: { select: { name: true } } },
      });

      return NextResponse.json({ created: [transfer] }, { status: 201 });
    }

    // ─── Create all transfers at once ───────────────────────────────
    if (action === "all_transfers") {
      const { transfers } = data as {
        transfers: {
          fromOutletId: string;
          toOutletId: string;
          items: { productId: string; productPackageId?: string; quantity: number }[];
        }[];
      };

      const created = [];
      for (const t of transfers) {
        const transfer = await prisma.stockTransfer.create({
          data: {
            fromOutletId: t.fromOutletId,
            toOutletId: t.toOutletId,
            status: "DRAFT",
            transferredById: caller.id,
            notes: "Auto-generated by AI inventory balancer",
            items: {
              create: t.items.map((i) => ({
                productId: i.productId,
                productPackageId: i.productPackageId || null,
                quantity: i.quantity,
              })),
            },
          },
          select: { id: true, fromOutlet: { select: { name: true } }, toOutlet: { select: { name: true } } },
        });
        created.push(transfer);
      }

      return NextResponse.json({ created }, { status: 201 });
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 });
  } catch (err) {
    console.error("[ai-decisions/execute] Error:", err);
    return NextResponse.json({ error: "Failed to execute decision" }, { status: 500 });
  }
}
