-- Live index snapshot — production project kqdcdhpnyuwrxqhbuyfl,
-- public schema, captured 2026-06-12 via pg_indexes.
--
-- WHY THIS EXISTS: an audit found dozens of indexes live in production
-- that exist in no committed migration file (applied directly over
-- time). schema.prisma + the migration folders therefore under-state
-- reality. This file is the authoritative index inventory for disaster
-- recovery: after restoring tables from the baseline + app migrations,
-- apply this to restore every index. Regenerate after index changes:
--
--   SELECT string_agg(indexdef || ';', E'\n' ORDER BY tablename, indexname)
--   FROM pg_indexes WHERE schemaname='public';
--
-- NOTE: includes PK/unique-constraint indexes that table DDL also
-- creates — duplicates error harmlessly if applied over existing
-- tables.

CREATE INDEX "ActivityLog_module_createdAt_idx" ON public."ActivityLog" USING btree (module, "createdAt");
CREATE UNIQUE INDEX "ActivityLog_pkey" ON public."ActivityLog" USING btree (id);
CREATE INDEX "ActivityLog_userId_createdAt_idx" ON public."ActivityLog" USING btree ("userId", "createdAt");
CREATE INDEX "idx_ActivityLog_userId" ON public."ActivityLog" USING btree ("userId");
CREATE UNIQUE INDEX "AppConfig_pkey" ON public."AppConfig" USING btree (key);
CREATE UNIQUE INDEX "ApprovalRule_pkey" ON public."ApprovalRule" USING btree (id);
CREATE INDEX "AuditReport_auditeeId_date_idx" ON public."AuditReport" USING btree ("auditeeId", date);
CREATE INDEX "AuditReport_auditorId_date_idx" ON public."AuditReport" USING btree ("auditorId", date);
CREATE INDEX "AuditReport_outletId_date_idx" ON public."AuditReport" USING btree ("outletId", date);
CREATE UNIQUE INDEX "AuditReport_pkey" ON public."AuditReport" USING btree (id);
CREATE INDEX "AuditReport_status_idx" ON public."AuditReport" USING btree (status);
CREATE INDEX "AuditReport_templateId_idx" ON public."AuditReport" USING btree ("templateId");
CREATE INDEX "idx_AuditReport_auditeeId" ON public."AuditReport" USING btree ("auditeeId");
CREATE INDEX "idx_AuditReport_auditorId" ON public."AuditReport" USING btree ("auditorId");
CREATE INDEX "idx_AuditReport_outletId" ON public."AuditReport" USING btree ("outletId");
CREATE INDEX "idx_AuditReport_templateId" ON public."AuditReport" USING btree ("templateId");
CREATE UNIQUE INDEX "AuditReportItem_pkey" ON public."AuditReportItem" USING btree (id);
CREATE INDEX "AuditReportItem_reportId_idx" ON public."AuditReportItem" USING btree ("reportId");
CREATE INDEX "idx_AuditReportItem_reportId" ON public."AuditReportItem" USING btree ("reportId");
CREATE UNIQUE INDEX "AuditSection_pkey" ON public."AuditSection" USING btree (id);
CREATE INDEX "AuditSection_templateId_idx" ON public."AuditSection" USING btree ("templateId");
CREATE INDEX "idx_AuditSection_templateId" ON public."AuditSection" USING btree ("templateId");
CREATE UNIQUE INDEX "AuditSectionItem_pkey" ON public."AuditSectionItem" USING btree (id);
CREATE INDEX "AuditSectionItem_sectionId_idx" ON public."AuditSectionItem" USING btree ("sectionId");
CREATE INDEX "idx_AuditSectionItem_sectionId" ON public."AuditSectionItem" USING btree ("sectionId");
CREATE INDEX "AuditTemplate_auditTarget_idx" ON public."AuditTemplate" USING btree ("auditTarget");
CREATE INDEX "AuditTemplate_isActive_idx" ON public."AuditTemplate" USING btree ("isActive");
CREATE INDEX "AuditTemplate_jobRoleFilter_idx" ON public."AuditTemplate" USING gin ("jobRoleFilter");
CREATE UNIQUE INDEX "AuditTemplate_pkey" ON public."AuditTemplate" USING btree (id);
CREATE INDEX "AuditTemplate_roleType_idx" ON public."AuditTemplate" USING btree ("roleType");
CREATE INDEX "idx_AuditTemplate_createdById" ON public."AuditTemplate" USING btree ("createdById");
CREATE UNIQUE INDEX "BankStatement_pkey" ON public."BankStatement" USING btree (id);
CREATE INDEX "BankStatement_statementDate_idx" ON public."BankStatement" USING btree ("statementDate");
CREATE INDEX "idx_BankStatement_uploadedById" ON public."BankStatement" USING btree ("uploadedById");
CREATE INDEX "BankStatementLine_category_outletId_idx" ON public."BankStatementLine" USING btree (category, "outletId");
CREATE INDEX "BankStatementLine_outletId_txnDate_idx" ON public."BankStatementLine" USING btree ("outletId", "txnDate" DESC);
CREATE UNIQUE INDEX "BankStatementLine_pkey" ON public."BankStatementLine" USING btree (id);
CREATE INDEX "BankStatementLine_statementId_idx" ON public."BankStatementLine" USING btree ("statementId");
CREATE INDEX "BankStatementLine_txnDate_idx" ON public."BankStatementLine" USING btree ("txnDate");
CREATE INDEX "idx_BankStatementLine_outletId" ON public."BankStatementLine" USING btree ("outletId");
CREATE INDEX "idx_BankStatementLine_statementId" ON public."BankStatementLine" USING btree ("statementId");
CREATE INDEX "Checklist_assignedToId_date_idx" ON public."Checklist" USING btree ("assignedToId", date);
CREATE INDEX "Checklist_outletId_date_idx" ON public."Checklist" USING btree ("outletId", date);
CREATE UNIQUE INDEX "Checklist_pkey" ON public."Checklist" USING btree (id);
CREATE UNIQUE INDEX "Checklist_sopId_outletId_date_shift_assignedToId_timeSlot_key" ON public."Checklist" USING btree ("sopId", "outletId", date, shift, "assignedToId", "timeSlot") NULLS NOT DISTINCT;
CREATE INDEX "Checklist_status_idx" ON public."Checklist" USING btree (status);
CREATE INDEX "idx_Checklist_assignedToId" ON public."Checklist" USING btree ("assignedToId");
CREATE INDEX "idx_Checklist_completedById" ON public."Checklist" USING btree ("completedById");
CREATE INDEX "idx_Checklist_outletId" ON public."Checklist" USING btree ("outletId");
CREATE INDEX "idx_Checklist_sopId" ON public."Checklist" USING btree ("sopId");
CREATE INDEX "ChecklistItem_checklistId_idx" ON public."ChecklistItem" USING btree ("checklistId");
CREATE UNIQUE INDEX "ChecklistItem_pkey" ON public."ChecklistItem" USING btree (id);
CREATE INDEX "idx_ChecklistItem_checklistId" ON public."ChecklistItem" USING btree ("checklistId");
CREATE INDEX "idx_ChecklistItem_completedById" ON public."ChecklistItem" USING btree ("completedById");
CREATE UNIQUE INDEX "HrClaimBatch_batchNumber_key" ON public."HrClaimBatch" USING btree ("batchNumber");
CREATE UNIQUE INDEX "HrClaimBatch_pkey" ON public."HrClaimBatch" USING btree (id);
CREATE INDEX "HrClaimBatch_status_createdAt_idx" ON public."HrClaimBatch" USING btree (status, "createdAt" DESC);
CREATE INDEX "HrClaimBatch_userId_status_idx" ON public."HrClaimBatch" USING btree ("userId", status);
CREATE INDEX "InternalFeedback_outletId_createdAt_idx" ON public."InternalFeedback" USING btree ("outletId", "createdAt");
CREATE UNIQUE INDEX "InternalFeedback_pkey" ON public."InternalFeedback" USING btree (id);
CREATE INDEX "idx_InternalFeedback_outletId" ON public."InternalFeedback" USING btree ("outletId");
CREATE INDEX "Invoice_claimBatchId_idx" ON public."Invoice" USING btree ("claimBatchId");
CREATE INDEX "Invoice_expenseCategory_idx" ON public."Invoice" USING btree ("expenseCategory");
CREATE INDEX "Invoice_flags_gin_idx" ON public."Invoice" USING gin (flags jsonb_path_ops);
CREATE UNIQUE INDEX "Invoice_orderId_placeholder_unique" ON public."Invoice" USING btree ("orderId") WHERE (("orderId" IS NOT NULL) AND (status = 'PENDING'::"InvoiceStatus") AND ("dueDate" IS NULL) AND ("invoiceNumber" ~~ 'INV-%'::text));
CREATE INDEX "Invoice_outletId_idx" ON public."Invoice" USING btree ("outletId");
CREATE INDEX "Invoice_paidAt_idx" ON public."Invoice" USING btree ("paidAt") WHERE ("paidAt" IS NOT NULL);
CREATE UNIQUE INDEX "Invoice_pkey" ON public."Invoice" USING btree (id);
CREATE INDEX "Invoice_status_dueDate_idx" ON public."Invoice" USING btree (status, "dueDate");
CREATE UNIQUE INDEX "Invoice_supplierId_invoiceNumber_key" ON public."Invoice" USING btree ("supplierId", "invoiceNumber");
CREATE INDEX "idx_Invoice_claimBatchId" ON public."Invoice" USING btree ("claimBatchId");
CREATE INDEX "idx_Invoice_orderId" ON public."Invoice" USING btree ("orderId");
CREATE INDEX "idx_Invoice_supplierId" ON public."Invoice" USING btree ("supplierId");
CREATE INDEX "idx_Invoice_transferId" ON public."Invoice" USING btree ("transferId");
CREATE INDEX invoice_ai_prefilled_idx ON public."Invoice" USING btree ("aiPrefilledAt") WHERE ("aiPrefilledAt" IS NOT NULL);
CREATE UNIQUE INDEX "ItemGroup_name_key" ON public."ItemGroup" USING btree (name);
CREATE UNIQUE INDEX "ItemGroup_pkey" ON public."ItemGroup" USING btree (id);
CREATE UNIQUE INDEX "ItemGroup_slug_key" ON public."ItemGroup" USING btree (slug);
CREATE UNIQUE INDEX "Menu_pkey" ON public."Menu" USING btree (id);
CREATE UNIQUE INDEX "Menu_storehubId_key" ON public."Menu" USING btree ("storehubId");
CREATE UNIQUE INDEX "MenuIngredient_menuId_productId_key" ON public."MenuIngredient" USING btree ("menuId", "productId");
CREATE UNIQUE INDEX "MenuIngredient_pkey" ON public."MenuIngredient" USING btree (id);
CREATE INDEX "idx_MenuIngredient_menuId" ON public."MenuIngredient" USING btree ("menuId");
CREATE INDEX "idx_MenuIngredient_productId" ON public."MenuIngredient" USING btree ("productId");
CREATE UNIQUE INDEX "Order_clientRequestId_key" ON public."Order" USING btree ("clientRequestId") WHERE ("clientRequestId" IS NOT NULL);
CREATE INDEX "Order_expenseCategory_idx" ON public."Order" USING btree ("expenseCategory");
CREATE UNIQUE INDEX "Order_orderNumber_key" ON public."Order" USING btree ("orderNumber");
CREATE INDEX "Order_outletId_createdAt_idx" ON public."Order" USING btree ("outletId", "createdAt" DESC);
CREATE UNIQUE INDEX "Order_pkey" ON public."Order" USING btree (id);
CREATE INDEX "Order_status_createdAt_idx" ON public."Order" USING btree (status, "createdAt" DESC);
CREATE INDEX "idx_Order_approvedById" ON public."Order" USING btree ("approvedById");
CREATE INDEX "idx_Order_claimedById" ON public."Order" USING btree ("claimedById");
CREATE INDEX "idx_Order_createdById" ON public."Order" USING btree ("createdById");
CREATE INDEX "idx_Order_outletId" ON public."Order" USING btree ("outletId");
CREATE INDEX "idx_Order_supplierId" ON public."Order" USING btree ("supplierId");
CREATE UNIQUE INDEX "OrderItem_orderId_productId_productPackageId_key" ON public."OrderItem" USING btree ("orderId", "productId", "productPackageId");
CREATE UNIQUE INDEX "OrderItem_pkey" ON public."OrderItem" USING btree (id);
CREATE INDEX "idx_OrderItem_orderId" ON public."OrderItem" USING btree ("orderId");
CREATE INDEX "idx_OrderItem_productId" ON public."OrderItem" USING btree ("productId");
CREATE INDEX "idx_OrderItem_productPackageId" ON public."OrderItem" USING btree ("productPackageId");
CREATE UNIQUE INDEX "Outlet_code_key" ON public."Outlet" USING btree (code);
CREATE UNIQUE INDEX "Outlet_pickupStoreId_key" ON public."Outlet" USING btree ("pickupStoreId");
CREATE UNIQUE INDEX "Outlet_pkey" ON public."Outlet" USING btree (id);
CREATE UNIQUE INDEX "Outlet_storehubId_key" ON public."Outlet" USING btree ("storehubId");
CREATE INDEX outlet_grab_merchant_id_idx ON public."Outlet" USING btree ("grabMerchantId") WHERE ("grabMerchantId" IS NOT NULL);
CREATE UNIQUE INDEX "OutletProduct_outletId_productId_key" ON public."OutletProduct" USING btree ("outletId", "productId");
CREATE UNIQUE INDEX "OutletProduct_pkey" ON public."OutletProduct" USING btree (id);
CREATE INDEX "idx_OutletProduct_outletId" ON public."OutletProduct" USING btree ("outletId");
CREATE INDEX "idx_OutletProduct_productId" ON public."OutletProduct" USING btree ("productId");
CREATE INDEX "ParLevel_outletId_idx" ON public."ParLevel" USING btree ("outletId");
CREATE UNIQUE INDEX "ParLevel_pkey" ON public."ParLevel" USING btree (id);
CREATE UNIQUE INDEX "ParLevel_productId_outletId_key" ON public."ParLevel" USING btree ("productId", "outletId");
CREATE INDEX "idx_ParLevel_outletId" ON public."ParLevel" USING btree ("outletId");
CREATE INDEX "idx_ParLevel_productId" ON public."ParLevel" USING btree ("productId");
CREATE INDEX "PasswordResetToken_expiresAt_idx" ON public."PasswordResetToken" USING btree ("expiresAt");
CREATE UNIQUE INDEX "PasswordResetToken_pkey" ON public."PasswordResetToken" USING btree (id);
CREATE UNIQUE INDEX "PasswordResetToken_tokenHash_key" ON public."PasswordResetToken" USING btree ("tokenHash");
CREATE INDEX "PasswordResetToken_userId_idx" ON public."PasswordResetToken" USING btree ("userId");
CREATE INDEX "idx_PasswordResetToken_userId" ON public."PasswordResetToken" USING btree ("userId");
CREATE UNIQUE INDEX "PriceHistory_pkey" ON public."PriceHistory" USING btree (id);
CREATE INDEX "PriceHistory_supplierId_changedAt_idx" ON public."PriceHistory" USING btree ("supplierId", "changedAt");
CREATE INDEX "idx_PriceHistory_supplierId" ON public."PriceHistory" USING btree ("supplierId");
CREATE UNIQUE INDEX "Product_pkey" ON public."Product" USING btree (id);
CREATE UNIQUE INDEX "Product_sku_key" ON public."Product" USING btree (sku);
CREATE INDEX "idx_Product_groupId" ON public."Product" USING btree ("groupId");
CREATE UNIQUE INDEX "ProductPackage_pkey" ON public."ProductPackage" USING btree (id);
CREATE INDEX "idx_ProductPackage_containsPackageId" ON public."ProductPackage" USING btree ("containsPackageId");
CREATE INDEX "idx_ProductPackage_productId" ON public."ProductPackage" USING btree ("productId");
CREATE INDEX "Receiving_outletId_receivedAt_idx" ON public."Receiving" USING btree ("outletId", "receivedAt" DESC);
CREATE UNIQUE INDEX "Receiving_pkey" ON public."Receiving" USING btree (id);
CREATE INDEX "idx_Receiving_orderId" ON public."Receiving" USING btree ("orderId");
CREATE INDEX "idx_Receiving_outletId" ON public."Receiving" USING btree ("outletId");
CREATE INDEX "idx_Receiving_receivedById" ON public."Receiving" USING btree ("receivedById");
CREATE INDEX "idx_Receiving_supplierId" ON public."Receiving" USING btree ("supplierId");
CREATE INDEX "idx_Receiving_transferId" ON public."Receiving" USING btree ("transferId");
CREATE UNIQUE INDEX "ReceivingItem_pkey" ON public."ReceivingItem" USING btree (id);
CREATE INDEX "idx_ReceivingItem_productId" ON public."ReceivingItem" USING btree ("productId");
CREATE INDEX "idx_ReceivingItem_productPackageId" ON public."ReceivingItem" USING btree ("productPackageId");
CREATE INDEX "idx_ReceivingItem_receivingId" ON public."ReceivingItem" USING btree ("receivingId");
CREATE INDEX "RecurringExpense_isActive_nextDueDate_idx" ON public."RecurringExpense" USING btree ("isActive", "nextDueDate");
CREATE UNIQUE INDEX "RecurringExpense_pkey" ON public."RecurringExpense" USING btree (id);
CREATE INDEX "idx_RecurringExpense_outletId" ON public."RecurringExpense" USING btree ("outletId");
CREATE UNIQUE INDEX "ReviewSettings_outletId_key" ON public."ReviewSettings" USING btree ("outletId");
CREATE UNIQUE INDEX "ReviewSettings_pkey" ON public."ReviewSettings" USING btree (id);
CREATE INDEX "idx_ReviewSettings_outletId" ON public."ReviewSettings" USING btree ("outletId");
CREATE INDEX "SalesTarget_effectiveFrom_idx" ON public."SalesTarget" USING btree ("effectiveFrom");
CREATE UNIQUE INDEX "SalesTarget_pkey" ON public."SalesTarget" USING btree (id);
CREATE INDEX "SalesTarget_roundKey_dayType_isActive_idx" ON public."SalesTarget" USING btree ("roundKey", "dayType", "isActive");
CREATE INDEX "SalesTransaction_menuId_idx" ON public."SalesTransaction" USING btree ("menuId");
CREATE INDEX "SalesTransaction_outletId_transactedAt_idx" ON public."SalesTransaction" USING btree ("outletId", "transactedAt");
CREATE UNIQUE INDEX "SalesTransaction_pkey" ON public."SalesTransaction" USING btree (id);
CREATE UNIQUE INDEX "SalesTransaction_storehubTxId_key" ON public."SalesTransaction" USING btree ("storehubTxId");
CREATE INDEX "idx_SalesTransaction_menuId" ON public."SalesTransaction" USING btree ("menuId");
CREATE INDEX "idx_SalesTransaction_outletId" ON public."SalesTransaction" USING btree ("outletId");
CREATE INDEX "ShortLink_createdAt_idx" ON public."ShortLink" USING btree ("createdAt");
CREATE UNIQUE INDEX "ShortLink_pkey" ON public."ShortLink" USING btree (id);
CREATE INDEX "Sop_categoryId_idx" ON public."Sop" USING btree ("categoryId");
CREATE UNIQUE INDEX "Sop_pkey" ON public."Sop" USING btree (id);
CREATE INDEX "Sop_status_idx" ON public."Sop" USING btree (status);
CREATE INDEX "idx_Sop_categoryId" ON public."Sop" USING btree ("categoryId");
CREATE INDEX "idx_Sop_createdById" ON public."Sop" USING btree ("createdById");
CREATE UNIQUE INDEX "SopCategory_name_key" ON public."SopCategory" USING btree (name);
CREATE UNIQUE INDEX "SopCategory_pkey" ON public."SopCategory" USING btree (id);
CREATE UNIQUE INDEX "SopCategory_slug_key" ON public."SopCategory" USING btree (slug);
CREATE INDEX "SopOutlet_outletId_idx" ON public."SopOutlet" USING btree ("outletId");
CREATE UNIQUE INDEX "SopOutlet_pkey" ON public."SopOutlet" USING btree (id);
CREATE UNIQUE INDEX "SopOutlet_sopId_outletId_key" ON public."SopOutlet" USING btree ("sopId", "outletId");
CREATE INDEX "idx_SopOutlet_outletId" ON public."SopOutlet" USING btree ("outletId");
CREATE INDEX "idx_SopOutlet_sopId" ON public."SopOutlet" USING btree ("sopId");
CREATE INDEX "SopSchedule_assignedToId_idx" ON public."SopSchedule" USING btree ("assignedToId");
CREATE INDEX "SopSchedule_outletId_idx" ON public."SopSchedule" USING btree ("outletId");
CREATE UNIQUE INDEX "SopSchedule_pkey" ON public."SopSchedule" USING btree (id);
CREATE UNIQUE INDEX "SopSchedule_sopId_outletId_assignedToId_shift_key" ON public."SopSchedule" USING btree ("sopId", "outletId", "assignedToId", shift);
CREATE INDEX "idx_SopSchedule_assignedToId" ON public."SopSchedule" USING btree ("assignedToId");
CREATE INDEX "idx_SopSchedule_outletId" ON public."SopSchedule" USING btree ("outletId");
CREATE INDEX "idx_SopSchedule_sopId" ON public."SopSchedule" USING btree ("sopId");
CREATE UNIQUE INDEX "SopStep_pkey" ON public."SopStep" USING btree (id);
CREATE INDEX "SopStep_sopId_idx" ON public."SopStep" USING btree ("sopId");
CREATE UNIQUE INDEX "SopStep_sopId_stepNumber_key" ON public."SopStep" USING btree ("sopId", "stepNumber");
CREATE INDEX "idx_SopStep_sopId" ON public."SopStep" USING btree ("sopId");
CREATE UNIQUE INDEX "StockAdjustment_pkey" ON public."StockAdjustment" USING btree (id);
CREATE INDEX "idx_StockAdjustment_adjustedById" ON public."StockAdjustment" USING btree ("adjustedById");
CREATE INDEX "idx_StockAdjustment_outletId" ON public."StockAdjustment" USING btree ("outletId");
CREATE INDEX "idx_StockAdjustment_productId" ON public."StockAdjustment" USING btree ("productId");
CREATE UNIQUE INDEX "StockBalance_outletId_productId_productPackageId_key" ON public."StockBalance" USING btree ("outletId", "productId", "productPackageId");
CREATE UNIQUE INDEX "StockBalance_pkey" ON public."StockBalance" USING btree (id);
CREATE INDEX "idx_StockBalance_outletId" ON public."StockBalance" USING btree ("outletId");
CREATE INDEX "idx_StockBalance_productId" ON public."StockBalance" USING btree ("productId");
CREATE INDEX "idx_StockBalance_productPackageId" ON public."StockBalance" USING btree ("productPackageId");
CREATE UNIQUE INDEX "StockCount_pkey" ON public."StockCount" USING btree (id);
CREATE INDEX "idx_StockCount_countedById" ON public."StockCount" USING btree ("countedById");
CREATE INDEX "idx_StockCount_outletId" ON public."StockCount" USING btree ("outletId");
CREATE UNIQUE INDEX "StockCountItem_count_product_pkg_key" ON public."StockCountItem" USING btree ("stockCountId", "productId", "productPackageId");
CREATE UNIQUE INDEX "StockCountItem_pkey" ON public."StockCountItem" USING btree (id);
CREATE UNIQUE INDEX "StockCountItem_stockCountId_productId_productPackageId_key" ON public."StockCountItem" USING btree ("stockCountId", "productId", "productPackageId");
CREATE INDEX "idx_StockCountItem_productId" ON public."StockCountItem" USING btree ("productId");
CREATE INDEX "idx_StockCountItem_productPackageId" ON public."StockCountItem" USING btree ("productPackageId");
CREATE INDEX "idx_StockCountItem_stockCountId" ON public."StockCountItem" USING btree ("stockCountId");
CREATE UNIQUE INDEX "StockTransfer_pkey" ON public."StockTransfer" USING btree (id);
CREATE INDEX "idx_StockTransfer_approvedById" ON public."StockTransfer" USING btree ("approvedById");
CREATE INDEX "idx_StockTransfer_fromOutletId" ON public."StockTransfer" USING btree ("fromOutletId");
CREATE INDEX "idx_StockTransfer_receivedById" ON public."StockTransfer" USING btree ("receivedById");
CREATE INDEX "idx_StockTransfer_rejectedById" ON public."StockTransfer" USING btree ("rejectedById");
CREATE INDEX "idx_StockTransfer_toOutletId" ON public."StockTransfer" USING btree ("toOutletId");
CREATE INDEX "idx_StockTransfer_transferredById" ON public."StockTransfer" USING btree ("transferredById");
CREATE UNIQUE INDEX "StockTransferItem_pkey" ON public."StockTransferItem" USING btree (id);
CREATE INDEX "idx_StockTransferItem_productId" ON public."StockTransferItem" USING btree ("productId");
CREATE INDEX "idx_StockTransferItem_productPackageId" ON public."StockTransferItem" USING btree ("productPackageId");
CREATE INDEX "idx_StockTransferItem_transferId" ON public."StockTransferItem" USING btree ("transferId");
CREATE UNIQUE INDEX "StorageArea_name_key" ON public."StorageArea" USING btree (name);
CREATE UNIQUE INDEX "StorageArea_pkey" ON public."StorageArea" USING btree (id);
CREATE UNIQUE INDEX "StorageArea_slug_key" ON public."StorageArea" USING btree (slug);
CREATE INDEX "StorehubSync_outletId_syncType_lastSyncAt_idx" ON public."StorehubSync" USING btree ("outletId", "syncType", "lastSyncAt");
CREATE UNIQUE INDEX "StorehubSync_pkey" ON public."StorehubSync" USING btree (id);
CREATE INDEX "idx_StorehubSync_outletId" ON public."StorehubSync" USING btree ("outletId");
CREATE UNIQUE INDEX "Supplier_pkey" ON public."Supplier" USING btree (id);
CREATE UNIQUE INDEX "Supplier_supplierCode_key" ON public."Supplier" USING btree ("supplierCode");
CREATE UNIQUE INDEX "SupplierProduct_pkey" ON public."SupplierProduct" USING btree (id);
CREATE INDEX "SupplierProduct_supplierId_idx" ON public."SupplierProduct" USING btree ("supplierId");
CREATE UNIQUE INDEX "SupplierProduct_supplierId_productId_productPackageId_key" ON public."SupplierProduct" USING btree ("supplierId", "productId", "productPackageId");
CREATE INDEX "idx_SupplierProduct_productId" ON public."SupplierProduct" USING btree ("productId");
CREATE INDEX "idx_SupplierProduct_productPackageId" ON public."SupplierProduct" USING btree ("productPackageId");
CREATE INDEX "idx_SupplierProduct_supplierId" ON public."SupplierProduct" USING btree ("supplierId");
CREATE UNIQUE INDEX "User_email_key" ON public."User" USING btree (email);
CREATE UNIQUE INDEX "User_phone_key" ON public."User" USING btree (phone);
CREATE UNIQUE INDEX "User_pkey" ON public."User" USING btree (id);
CREATE UNIQUE INDEX "User_username_key" ON public."User" USING btree (username);
CREATE INDEX "idx_User_outletId" ON public."User" USING btree ("outletId");
CREATE UNIQUE INDEX outlet_settings_pkey ON public._outlet_settings_backup USING btree (store_id);
CREATE UNIQUE INDEX outlets_pkey ON public._outlets_backup USING btree (id);
CREATE UNIQUE INDEX admin_claimables_pkey ON public.admin_claimables USING btree (id);
CREATE INDEX idx_admin_claimables_brand_active ON public.admin_claimables USING btree (brand_id, is_active);
CREATE INDEX idx_admin_claimables_voucher_template_id ON public.admin_claimables USING btree (voucher_template_id);
CREATE UNIQUE INDEX admin_claimables_claimed_pkey ON public.admin_claimables_claimed USING btree (claimable_id, member_id);
CREATE INDEX idx_admin_claimables_claimed_claimable_id ON public.admin_claimables_claimed USING btree (claimable_id);
CREATE INDEX idx_admin_claimables_claimed_voucher_id ON public.admin_claimables_claimed USING btree (voucher_id);
CREATE UNIQUE INDEX ads_account_customer_id_key ON public.ads_account USING btree (customer_id);
CREATE UNIQUE INDEX ads_account_pkey ON public.ads_account USING btree (id);
CREATE INDEX idx_ads_account_outlet ON public.ads_account USING btree (outlet_id);
CREATE INDEX idx_ads_account_outlet_id ON public.ads_account USING btree (outlet_id);
CREATE UNIQUE INDEX ads_campaign_account_id_campaign_id_key ON public.ads_campaign USING btree (account_id, campaign_id);
CREATE UNIQUE INDEX ads_campaign_pkey ON public.ads_campaign USING btree (id);
CREATE INDEX idx_ads_campaign_account ON public.ads_campaign USING btree (account_id);
CREATE INDEX idx_ads_campaign_account_id ON public.ads_campaign USING btree (account_id);
CREATE INDEX idx_ads_campaign_outlet ON public.ads_campaign USING btree (outlet_id);
CREATE INDEX idx_ads_campaign_outlet_id ON public.ads_campaign USING btree (outlet_id);
CREATE INDEX idx_ads_campaign_status ON public.ads_campaign USING btree (status);
CREATE UNIQUE INDEX ads_conversion_daily_date_campaign_id_conversion_action_id_key ON public.ads_conversion_daily USING btree (date, campaign_id, conversion_action_id);
CREATE UNIQUE INDEX ads_conversion_daily_pkey ON public.ads_conversion_daily USING btree (id);
CREATE INDEX idx_ads_conv_daily_campaign ON public.ads_conversion_daily USING btree (campaign_id, date DESC);
CREATE INDEX idx_ads_conv_daily_category ON public.ads_conversion_daily USING btree (conversion_category);
CREATE INDEX idx_ads_conv_daily_date ON public.ads_conversion_daily USING btree (date DESC);
CREATE INDEX idx_ads_conversion_daily_account_id ON public.ads_conversion_daily USING btree (account_id);
CREATE INDEX idx_ads_conversion_daily_campaign_id ON public.ads_conversion_daily USING btree (campaign_id);
CREATE UNIQUE INDEX ads_invoice_invoice_id_key ON public.ads_invoice USING btree (invoice_id);
CREATE UNIQUE INDEX ads_invoice_pkey ON public.ads_invoice USING btree (id);
CREATE INDEX idx_ads_invoice_account ON public.ads_invoice USING btree (account_id, issue_date DESC);
CREATE INDEX idx_ads_invoice_account_id ON public.ads_invoice USING btree (account_id);
CREATE INDEX idx_ads_invoice_period ON public.ads_invoice USING btree (billing_period_start DESC);
CREATE INDEX idx_ads_invoice_status ON public.ads_invoice USING btree (status);
CREATE UNIQUE INDEX ads_keyword_metric_date_campaign_id_ad_group_id_criterion_i_key ON public.ads_keyword_metric USING btree (date, campaign_id, ad_group_id, criterion_id);
CREATE UNIQUE INDEX ads_keyword_metric_pkey ON public.ads_keyword_metric USING btree (id);
CREATE INDEX idx_ads_keyword_campaign ON public.ads_keyword_metric USING btree (campaign_id, date DESC);
CREATE INDEX idx_ads_keyword_date ON public.ads_keyword_metric USING btree (date DESC);
CREATE INDEX idx_ads_keyword_metric_campaign_id ON public.ads_keyword_metric USING btree (campaign_id);
CREATE UNIQUE INDEX ads_metric_daily_date_account_id_campaign_id_key ON public.ads_metric_daily USING btree (date, account_id, campaign_id);
CREATE UNIQUE INDEX ads_metric_daily_pkey ON public.ads_metric_daily USING btree (id);
CREATE INDEX idx_ads_metric_daily_account ON public.ads_metric_daily USING btree (account_id, date DESC);
CREATE INDEX idx_ads_metric_daily_account_id ON public.ads_metric_daily USING btree (account_id);
CREATE INDEX idx_ads_metric_daily_campaign ON public.ads_metric_daily USING btree (campaign_id, date DESC);
CREATE INDEX idx_ads_metric_daily_campaign_id ON public.ads_metric_daily USING btree (campaign_id);
CREATE INDEX idx_ads_metric_daily_date ON public.ads_metric_daily USING btree (date DESC);
CREATE UNIQUE INDEX ads_payment_pkey ON public.ads_payment USING btree (id);
CREATE UNIQUE INDEX ads_payment_pop_telegram_token_key ON public.ads_payment USING btree (pop_telegram_token);
CREATE INDEX idx_ads_payment_campaign ON public.ads_payment USING btree (campaign_id);
CREATE INDEX idx_ads_payment_campaign_id ON public.ads_payment USING btree (campaign_id);
CREATE INDEX idx_ads_payment_outlet ON public.ads_payment USING btree (outlet_id);
CREATE INDEX idx_ads_payment_outlet_id ON public.ads_payment USING btree (outlet_id);
CREATE INDEX idx_ads_payment_paid_by_user_id ON public.ads_payment USING btree (paid_by_user_id);
CREATE UNIQUE INDEX idx_ads_payment_scope ON public.ads_payment USING btree (year_month, COALESCE(outlet_id, ''::text), COALESCE(campaign_id, ''::text)) WHERE (status <> 'VOID'::text);
CREATE INDEX idx_ads_payment_status ON public.ads_payment USING btree (status);
CREATE INDEX idx_ads_payment_tg_chat ON public.ads_payment USING btree (pop_telegram_chat_id) WHERE (pop_telegram_chat_id IS NOT NULL);
CREATE INDEX idx_ads_payment_ym ON public.ads_payment USING btree (year_month DESC);
CREATE UNIQUE INDEX ads_settings_pkey ON public.ads_settings USING btree (id);
CREATE UNIQUE INDEX ads_sync_log_pkey ON public.ads_sync_log USING btree (id);
CREATE INDEX idx_ads_sync_log_account_id ON public.ads_sync_log USING btree (account_id);
CREATE INDEX idx_ads_sync_log_kind ON public.ads_sync_log USING btree (kind, started_at DESC);
CREATE INDEX idx_ads_sync_log_started ON public.ads_sync_log USING btree (started_at DESC);
CREATE INDEX advisor_messages_chat_created_idx ON public.advisor_messages USING btree (chat_id, created_at DESC);
CREATE UNIQUE INDEX advisor_messages_pkey ON public.advisor_messages USING btree (id);
CREATE UNIQUE INDEX agent_insights_cache_pkey ON public.agent_insights_cache USING btree (id);
CREATE INDEX idx_agent_insights_cache_agent_generated ON public.agent_insights_cache USING btree (agent_name, generated_at DESC);
CREATE UNIQUE INDEX app_config_pkey ON public.app_config USING btree (key);
CREATE UNIQUE INDEX app_settings_pkey ON public.app_settings USING btree (key);
CREATE UNIQUE INDEX brands_pkey ON public.brands USING btree (id);
CREATE UNIQUE INDEX brands_slug_key ON public.brands USING btree (slug);
CREATE UNIQUE INDEX campaigns_pkey ON public.campaigns USING btree (id);
CREATE INDEX idx_campaigns_brand_active ON public.campaigns USING btree (brand_id, is_active);
CREATE INDEX idx_campaigns_brand_id ON public.campaigns USING btree (brand_id);
CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);
CREATE INDEX expo_push_tokens_member_id_idx ON public.expo_push_tokens USING btree (member_id);
CREATE INDEX expo_push_tokens_phone_idx ON public.expo_push_tokens USING btree (phone);
CREATE UNIQUE INDEX expo_push_tokens_pkey ON public.expo_push_tokens USING btree (id);
CREATE UNIQUE INDEX expo_push_tokens_token_key ON public.expo_push_tokens USING btree (token);
CREATE UNIQUE INDEX fin_accounts_pkey ON public.fin_accounts USING btree (code);
CREATE INDEX idx_fin_accounts_parent ON public.fin_accounts USING btree (parent_code);
CREATE INDEX idx_fin_accounts_parent_code ON public.fin_accounts USING btree (parent_code);
CREATE INDEX idx_fin_accounts_type ON public.fin_accounts USING btree (type);
CREATE UNIQUE INDEX fin_agent_decisions_pkey ON public.fin_agent_decisions USING btree (id);
CREATE INDEX idx_fin_agent_decisions_agent ON public.fin_agent_decisions USING btree (agent, created_at);
CREATE INDEX idx_fin_agent_decisions_corrected ON public.fin_agent_decisions USING btree (corrected) WHERE corrected;
CREATE INDEX idx_fin_agent_decisions_corrected_by ON public.fin_agent_decisions USING btree (corrected_by);
CREATE UNIQUE INDEX fin_audit_log_pkey ON public.fin_audit_log USING btree (id);
CREATE INDEX idx_fin_audit_log_row ON public.fin_audit_log USING btree (table_name, row_id);
CREATE INDEX idx_fin_audit_log_time ON public.fin_audit_log USING btree (occurred_at);
CREATE UNIQUE INDEX fin_bank_transactions_bank_account_code_txn_date_amount_des_key ON public.fin_bank_transactions USING btree (bank_account_code, txn_date, amount, description, reference);
CREATE UNIQUE INDEX fin_bank_transactions_pkey ON public.fin_bank_transactions USING btree (id);
CREATE INDEX idx_fin_bank_transactions_bank_account_code ON public.fin_bank_transactions USING btree (bank_account_code);
CREATE INDEX idx_fin_bank_transactions_raw_line_id ON public.fin_bank_transactions USING btree (raw_line_id);
CREATE INDEX idx_fin_bank_txn_account_date ON public.fin_bank_transactions USING btree (bank_account_code, txn_date);
CREATE INDEX idx_fin_bank_txn_status ON public.fin_bank_transactions USING btree (status);
CREATE UNIQUE INDEX fin_bills_pkey ON public.fin_bills USING btree (id);
CREATE INDEX idx_fin_bills_company ON public.fin_bills USING btree (company_id);
CREATE INDEX idx_fin_bills_company_id ON public.fin_bills USING btree (company_id);
CREATE INDEX idx_fin_bills_date ON public.fin_bills USING btree (bill_date);
CREATE INDEX idx_fin_bills_due ON public.fin_bills USING btree (due_date) WHERE (payment_status = ANY (ARRAY['unpaid'::text, 'partial'::text]));
CREATE INDEX idx_fin_bills_outlet_id ON public.fin_bills USING btree (outlet_id);
CREATE INDEX idx_fin_bills_source_doc_id ON public.fin_bills USING btree (source_doc_id);
CREATE INDEX idx_fin_bills_status ON public.fin_bills USING btree (payment_status);
CREATE INDEX idx_fin_bills_supplier ON public.fin_bills USING btree (supplier_id);
CREATE INDEX idx_fin_bills_supplier_id ON public.fin_bills USING btree (supplier_id);
CREATE INDEX idx_fin_bills_transaction_id ON public.fin_bills USING btree (transaction_id);
CREATE UNIQUE INDEX fin_companies_pkey ON public.fin_companies USING btree (id);
CREATE UNIQUE INDEX ux_fin_companies_default ON public.fin_companies USING btree (is_default) WHERE is_default;
CREATE UNIQUE INDEX fin_documents_pkey ON public.fin_documents USING btree (id);
CREATE UNIQUE INDEX fin_documents_source_source_ref_key ON public.fin_documents USING btree (source, source_ref);
CREATE INDEX idx_fin_documents_company ON public.fin_documents USING btree (company_id);
CREATE INDEX idx_fin_documents_company_id ON public.fin_documents USING btree (company_id);
CREATE INDEX idx_fin_documents_outlet ON public.fin_documents USING btree (outlet_id);
CREATE INDEX idx_fin_documents_outlet_id ON public.fin_documents USING btree (outlet_id);
CREATE INDEX idx_fin_documents_received ON public.fin_documents USING btree (received_at);
CREATE INDEX idx_fin_documents_source ON public.fin_documents USING btree (source, status);
CREATE UNIQUE INDEX fin_einvoice_submissions_pkey ON public.fin_einvoice_submissions USING btree (id);
CREATE INDEX idx_fin_einvoice_invoice ON public.fin_einvoice_submissions USING btree (invoice_id);
CREATE INDEX idx_fin_einvoice_status ON public.fin_einvoice_submissions USING btree (status);
CREATE INDEX idx_fin_einvoice_submissions_invoice_id ON public.fin_einvoice_submissions USING btree (invoice_id);
CREATE UNIQUE INDEX fin_exceptions_pkey ON public.fin_exceptions USING btree (id);
CREATE INDEX idx_fin_exceptions_company ON public.fin_exceptions USING btree (company_id);
CREATE INDEX idx_fin_exceptions_company_id ON public.fin_exceptions USING btree (company_id);
CREATE INDEX idx_fin_exceptions_related ON public.fin_exceptions USING btree (related_type, related_id);
CREATE INDEX idx_fin_exceptions_resolved_by ON public.fin_exceptions USING btree (resolved_by);
CREATE INDEX idx_fin_exceptions_status ON public.fin_exceptions USING btree (status, priority, created_at);
CREATE UNIQUE INDEX fin_fixed_assets_pkey ON public.fin_fixed_assets USING btree (id);
CREATE INDEX idx_fin_fixed_assets_account ON public.fin_fixed_assets USING btree (account_code);
CREATE INDEX idx_fin_fixed_assets_account_code ON public.fin_fixed_assets USING btree (account_code);
CREATE INDEX idx_fin_fixed_assets_company ON public.fin_fixed_assets USING btree (company_id);
CREATE INDEX idx_fin_fixed_assets_company_id ON public.fin_fixed_assets USING btree (company_id);
CREATE INDEX idx_fin_fixed_assets_outlet_id ON public.fin_fixed_assets USING btree (outlet_id);
CREATE INDEX idx_fin_fixed_assets_source_doc_id ON public.fin_fixed_assets USING btree (source_doc_id);
CREATE INDEX idx_fin_fixed_assets_status ON public.fin_fixed_assets USING btree (status);
CREATE UNIQUE INDEX fin_invoices_invoice_number_key ON public.fin_invoices USING btree (invoice_number);
CREATE UNIQUE INDEX fin_invoices_pkey ON public.fin_invoices USING btree (id);
CREATE INDEX idx_fin_invoices_channel ON public.fin_invoices USING btree (channel);
CREATE INDEX idx_fin_invoices_company ON public.fin_invoices USING btree (company_id);
CREATE INDEX idx_fin_invoices_company_id ON public.fin_invoices USING btree (company_id);
CREATE INDEX idx_fin_invoices_date ON public.fin_invoices USING btree (invoice_date);
CREATE INDEX idx_fin_invoices_outlet ON public.fin_invoices USING btree (outlet_id);
CREATE INDEX idx_fin_invoices_outlet_id ON public.fin_invoices USING btree (outlet_id);
CREATE INDEX idx_fin_invoices_source_doc_id ON public.fin_invoices USING btree (source_doc_id);
CREATE INDEX idx_fin_invoices_status ON public.fin_invoices USING btree (payment_status);
CREATE INDEX idx_fin_invoices_transaction_id ON public.fin_invoices USING btree (transaction_id);
CREATE UNIQUE INDEX fin_journal_lines_pkey ON public.fin_journal_lines USING btree (id);
CREATE INDEX idx_fin_journal_lines_account ON public.fin_journal_lines USING btree (account_code);
CREATE INDEX idx_fin_journal_lines_account_code ON public.fin_journal_lines USING btree (account_code);
CREATE INDEX idx_fin_journal_lines_outlet ON public.fin_journal_lines USING btree (outlet_id);
CREATE INDEX idx_fin_journal_lines_outlet_id ON public.fin_journal_lines USING btree (outlet_id);
CREATE INDEX idx_fin_journal_lines_transaction_id ON public.fin_journal_lines USING btree (transaction_id);
CREATE INDEX idx_fin_journal_lines_txn ON public.fin_journal_lines USING btree (transaction_id);
CREATE UNIQUE INDEX fin_matches_pkey ON public.fin_matches USING btree (id);
CREATE INDEX idx_fin_matches_bank ON public.fin_matches USING btree (bank_txn_id);
CREATE INDEX idx_fin_matches_bank_txn_id ON public.fin_matches USING btree (bank_txn_id);
CREATE INDEX idx_fin_matches_target ON public.fin_matches USING btree (matched_to_type, matched_to_id);
CREATE UNIQUE INDEX fin_outlet_companies_pkey ON public.fin_outlet_companies USING btree (outlet_id);
CREATE INDEX idx_fin_outlet_companies_company ON public.fin_outlet_companies USING btree (company_id);
CREATE INDEX idx_fin_outlet_companies_company_id ON public.fin_outlet_companies USING btree (company_id);
CREATE INDEX idx_fin_outlet_companies_outlet_id ON public.fin_outlet_companies USING btree (outlet_id);
CREATE INDEX idx_fin_periods_closed_by ON public.fin_periods USING btree (closed_by);
CREATE INDEX idx_fin_periods_company_id ON public.fin_periods USING btree (company_id);
CREATE INDEX idx_fin_periods_reopened_by ON public.fin_periods USING btree (reopened_by);
CREATE UNIQUE INDEX ux_fin_periods_company_period ON public.fin_periods USING btree (company_id, period);
CREATE UNIQUE INDEX fin_sst_filings_pkey ON public.fin_sst_filings USING btree (id);
CREATE INDEX idx_fin_sst_filings_company_id ON public.fin_sst_filings USING btree (company_id);
CREATE INDEX idx_fin_sst_filings_filed_by ON public.fin_sst_filings USING btree (filed_by);
CREATE UNIQUE INDEX ux_fin_sst_filings_company_period ON public.fin_sst_filings USING btree (company_id, period);
CREATE UNIQUE INDEX fin_transactions_pkey ON public.fin_transactions USING btree (id);
CREATE INDEX idx_fin_transactions_company ON public.fin_transactions USING btree (company_id);
CREATE INDEX idx_fin_transactions_company_id ON public.fin_transactions USING btree (company_id);
CREATE INDEX idx_fin_transactions_company_period ON public.fin_transactions USING btree (company_id, period);
CREATE INDEX idx_fin_transactions_date ON public.fin_transactions USING btree (txn_date);
CREATE INDEX idx_fin_transactions_doc ON public.fin_transactions USING btree (source_doc_id);
CREATE INDEX idx_fin_transactions_outlet ON public.fin_transactions USING btree (outlet_id);
CREATE INDEX idx_fin_transactions_outlet_id ON public.fin_transactions USING btree (outlet_id);
CREATE INDEX idx_fin_transactions_period ON public.fin_transactions USING btree (period);
CREATE INDEX idx_fin_transactions_reversed_by_id ON public.fin_transactions USING btree (reversed_by_id);
CREATE INDEX idx_fin_transactions_source_doc_id ON public.fin_transactions USING btree (source_doc_id);
CREATE INDEX idx_fin_transactions_status ON public.fin_transactions USING btree (status);
CREATE UNIQUE INDEX fin_user_roles_pkey ON public.fin_user_roles USING btree (user_id, role, scope_outlet_id);
CREATE INDEX idx_fin_user_roles_company ON public.fin_user_roles USING btree (company_id);
CREATE INDEX idx_fin_user_roles_company_id ON public.fin_user_roles USING btree (company_id);
CREATE INDEX idx_fin_user_roles_granted_by ON public.fin_user_roles USING btree (granted_by);
CREATE INDEX idx_fin_user_roles_scope_outlet_id ON public.fin_user_roles USING btree (scope_outlet_id);
CREATE INDEX idx_fin_user_roles_user ON public.fin_user_roles USING btree (user_id);
CREATE INDEX idx_fin_user_roles_user_id ON public.fin_user_roles USING btree (user_id);
CREATE UNIQUE INDEX hr_agent_runs_pkey ON public.hr_agent_runs USING btree (id);
CREATE INDEX idx_hr_agent_type ON public.hr_agent_runs USING btree (agent_type, started_at);
CREATE UNIQUE INDEX hr_attendance_logs_pkey ON public.hr_attendance_logs USING btree (id);
CREATE INDEX hr_attendance_logs_user_clockin_idx ON public.hr_attendance_logs USING btree (user_id, clock_in DESC);
CREATE INDEX idx_hr_att_ai_status ON public.hr_attendance_logs USING btree (ai_status);
CREATE INDEX idx_hr_att_outlet ON public.hr_attendance_logs USING btree (outlet_id, clock_in);
CREATE INDEX idx_hr_att_user_date ON public.hr_attendance_logs USING btree (user_id, clock_in);
CREATE INDEX idx_hr_attendance_logs_ot_approval_id ON public.hr_attendance_logs USING btree (ot_approval_id);
CREATE UNIQUE INDEX hr_attendance_pings_pkey ON public.hr_attendance_pings USING btree (id);
CREATE INDEX idx_hr_attendance_pings_attendance_log_id ON public.hr_attendance_pings USING btree (attendance_log_id);
CREATE INDEX idx_hr_attendance_pings_outlet_id ON public.hr_attendance_pings USING btree (outlet_id);
CREATE INDEX idx_hr_attendance_pings_user_id ON public.hr_attendance_pings USING btree (user_id);
CREATE INDEX idx_hr_pings_log ON public.hr_attendance_pings USING btree (attendance_log_id, created_at DESC);
CREATE INDEX idx_hr_pings_user_time ON public.hr_attendance_pings USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX hr_certification_reminders_certification_id_stage_key ON public.hr_certification_reminders USING btree (certification_id, stage);
CREATE UNIQUE INDEX hr_certification_reminders_pkey ON public.hr_certification_reminders USING btree (id);
CREATE INDEX idx_hr_certification_reminders_certification_id ON public.hr_certification_reminders USING btree (certification_id);
CREATE INDEX hr_certifications_expires_idx ON public.hr_certifications USING btree (expires_at) WHERE (expires_at IS NOT NULL);
CREATE UNIQUE INDEX hr_certifications_pkey ON public.hr_certifications USING btree (id);
CREATE INDEX hr_certifications_user_idx ON public.hr_certifications USING btree (user_id);
CREATE INDEX idx_hr_certifications_user_id ON public.hr_certifications USING btree (user_id);
CREATE UNIQUE INDEX hr_company_assets_pkey ON public.hr_company_assets USING btree (id);
CREATE INDEX idx_hr_assets_user_status ON public.hr_company_assets USING btree (user_id, status);
CREATE UNIQUE INDEX hr_company_settings_pkey ON public.hr_company_settings USING btree (id);
CREATE UNIQUE INDEX hr_compliance_events_pkey ON public.hr_compliance_events USING btree (id);
CREATE INDEX idx_hr_compliance_due_status ON public.hr_compliance_events USING btree (due_date, status);
CREATE UNIQUE INDEX hr_disciplinary_actions_pkey ON public.hr_disciplinary_actions USING btree (id);
CREATE INDEX idx_hr_disciplinary_actions_related_review_penalty_id ON public.hr_disciplinary_actions USING btree (related_review_penalty_id);
CREATE INDEX idx_hr_disciplinary_user_date ON public.hr_disciplinary_actions USING btree (user_id, issued_at DESC);
CREATE UNIQUE INDEX hr_employee_child_relief_pkey ON public.hr_employee_child_relief USING btree (id);
CREATE UNIQUE INDEX hr_employee_child_relief_user_id_year_key ON public.hr_employee_child_relief USING btree (user_id, year);
CREATE UNIQUE INDEX hr_employee_documents_pkey ON public.hr_employee_documents USING btree (id);
CREATE INDEX hr_employee_documents_type_idx ON public.hr_employee_documents USING btree (doc_type);
CREATE INDEX hr_employee_documents_user_id_idx ON public.hr_employee_documents USING btree (user_id, uploaded_at DESC);
CREATE UNIQUE INDEX hr_employee_family_pkey ON public.hr_employee_family USING btree (id);
CREATE INDEX idx_hr_employee_family_user ON public.hr_employee_family USING btree (user_id);
CREATE INDEX idx_hr_employee_family_user_id ON public.hr_employee_family USING btree (user_id);
CREATE INDEX hr_employee_profiles_completed_at_idx ON public.hr_employee_profiles USING btree (profile_completed_at);
CREATE UNIQUE INDEX hr_employee_profiles_pkey ON public.hr_employee_profiles USING btree (id);
CREATE UNIQUE INDEX hr_employee_profiles_user_id_key ON public.hr_employee_profiles USING btree (user_id);
CREATE INDEX idx_hr_emp_user ON public.hr_employee_profiles USING btree (user_id);
CREATE INDEX idx_hr_employee_profiles_manager ON public.hr_employee_profiles USING btree (manager_user_id);
CREATE INDEX idx_hr_employee_profiles_manager_user_id ON public.hr_employee_profiles USING btree (manager_user_id);
CREATE INDEX idx_hr_employee_profiles_preferred_outlet_id ON public.hr_employee_profiles USING btree (preferred_outlet_id);
CREATE UNIQUE INDEX hr_employee_recurring_items_pkey ON public.hr_employee_recurring_items USING btree (id);
CREATE INDEX idx_hr_employee_recurring_items_catalog_code ON public.hr_employee_recurring_items USING btree (catalog_code);
CREATE INDEX idx_hr_recurring_catalog ON public.hr_employee_recurring_items USING btree (catalog_code);
CREATE INDEX idx_hr_recurring_user ON public.hr_employee_recurring_items USING btree (user_id, effective_date DESC);
CREATE UNIQUE INDEX hr_employee_tax_reliefs_pkey ON public.hr_employee_tax_reliefs USING btree (id);
CREATE UNIQUE INDEX hr_employee_tax_reliefs_user_id_year_relief_code_key ON public.hr_employee_tax_reliefs USING btree (user_id, year, relief_code);
CREATE INDEX idx_hr_emp_relief_user_year ON public.hr_employee_tax_reliefs USING btree (user_id, year);
CREATE INDEX idx_hr_employee_tax_reliefs_relief_code ON public.hr_employee_tax_reliefs USING btree (relief_code);
CREATE UNIQUE INDEX hr_geofence_zones_pkey ON public.hr_geofence_zones USING btree (id);
CREATE INDEX idx_hr_geo_outlet ON public.hr_geofence_zones USING btree (outlet_id);
CREATE UNIQUE INDEX hr_job_history_pkey ON public.hr_job_history USING btree (id);
CREATE INDEX idx_hr_job_history_user ON public.hr_job_history USING btree (user_id, effective_date DESC);
CREATE UNIQUE INDEX hr_leave_balances_pkey ON public.hr_leave_balances USING btree (id);
CREATE UNIQUE INDEX hr_leave_balances_user_id_year_leave_type_key ON public.hr_leave_balances USING btree (user_id, year, leave_type);
CREATE INDEX idx_hr_lb_user ON public.hr_leave_balances USING btree (user_id, year);
CREATE UNIQUE INDEX hr_leave_policies_leave_type_key ON public.hr_leave_policies USING btree (leave_type);
CREATE UNIQUE INDEX hr_leave_policies_pkey ON public.hr_leave_policies USING btree (id);
CREATE UNIQUE INDEX hr_leave_requests_pkey ON public.hr_leave_requests USING btree (id);
CREATE INDEX idx_hr_leave_status ON public.hr_leave_requests USING btree (status);
CREATE INDEX idx_hr_leave_user ON public.hr_leave_requests USING btree (user_id, start_date);
CREATE UNIQUE INDEX hr_memo_acknowledgements_memo_id_user_id_key ON public.hr_memo_acknowledgements USING btree (memo_id, user_id);
CREATE UNIQUE INDEX hr_memo_acknowledgements_pkey ON public.hr_memo_acknowledgements USING btree (id);
CREATE INDEX idx_hr_memo_acknowledgements_memo_id ON public.hr_memo_acknowledgements USING btree (memo_id);
CREATE INDEX idx_hr_memo_acks_memo_id ON public.hr_memo_acknowledgements USING btree (memo_id);
CREATE INDEX idx_hr_memo_acks_user_id ON public.hr_memo_acknowledgements USING btree (user_id);
CREATE UNIQUE INDEX hr_memos_pkey ON public.hr_memos USING btree (id);
CREATE INDEX idx_hr_memos_issued_at ON public.hr_memos USING btree (issued_at DESC);
CREATE INDEX idx_hr_memos_status ON public.hr_memos USING btree (status);
CREATE INDEX idx_hr_memos_user ON public.hr_memos USING btree (user_id);
CREATE INDEX idx_hr_memos_user_ids ON public.hr_memos USING gin (user_ids);
CREATE UNIQUE INDEX hr_onboarding_progress_pkey ON public.hr_onboarding_progress USING btree (id);
CREATE UNIQUE INDEX hr_onboarding_progress_user_id_template_id_key ON public.hr_onboarding_progress USING btree (user_id, template_id);
CREATE INDEX idx_hr_onboarding_progress_template_id ON public.hr_onboarding_progress USING btree (template_id);
CREATE INDEX idx_hr_onboarding_progress_user ON public.hr_onboarding_progress USING btree (user_id);
CREATE UNIQUE INDEX hr_onboarding_templates_pkey ON public.hr_onboarding_templates USING btree (id);
CREATE UNIQUE INDEX hr_outlet_coverage_rules_pkey ON public.hr_outlet_coverage_rules USING btree (id);
CREATE UNIQUE INDEX hr_overtime_requests_pkey ON public.hr_overtime_requests USING btree (id);
CREATE INDEX idx_hr_ot_requests_outlet ON public.hr_overtime_requests USING btree (outlet_id);
CREATE INDEX idx_hr_ot_requests_status ON public.hr_overtime_requests USING btree (status);
CREATE INDEX idx_hr_ot_requests_user_date ON public.hr_overtime_requests USING btree (user_id, date);
CREATE INDEX idx_hr_overtime_requests_attendance_log_id ON public.hr_overtime_requests USING btree (attendance_log_id);
CREATE INDEX idx_hr_overtime_requests_outlet_id ON public.hr_overtime_requests USING btree (outlet_id);
CREATE INDEX idx_hr_overtime_requests_requested_by ON public.hr_overtime_requests USING btree (requested_by);
CREATE INDEX idx_hr_overtime_requests_reviewed_by ON public.hr_overtime_requests USING btree (reviewed_by);
CREATE INDEX idx_hr_overtime_requests_user_id ON public.hr_overtime_requests USING btree (user_id);
CREATE UNIQUE INDEX hr_payroll_cycles_pkey ON public.hr_payroll_cycles USING btree (id);
CREATE UNIQUE INDEX hr_payroll_item_catalog_code_key ON public.hr_payroll_item_catalog USING btree (code);
CREATE UNIQUE INDEX hr_payroll_item_catalog_pkey ON public.hr_payroll_item_catalog USING btree (id);
CREATE INDEX idx_hr_payroll_item_catalog_category ON public.hr_payroll_item_catalog USING btree (category);
CREATE UNIQUE INDEX hr_payroll_items_pkey ON public.hr_payroll_items USING btree (id);
CREATE INDEX idx_hr_payroll_items_payroll_run_id ON public.hr_payroll_items USING btree (payroll_run_id);
CREATE INDEX idx_hr_pi_run ON public.hr_payroll_items USING btree (payroll_run_id);
CREATE INDEX idx_hr_pi_user ON public.hr_payroll_items USING btree (user_id);
CREATE INDEX hr_payroll_runs_cycle_idx ON public.hr_payroll_runs USING btree (cycle_type, period_start DESC);
CREATE INDEX hr_payroll_runs_period_idx ON public.hr_payroll_runs USING btree (period_year DESC, period_month DESC);
CREATE UNIQUE INDEX hr_payroll_runs_period_month_period_year_key ON public.hr_payroll_runs USING btree (period_month, period_year);
CREATE UNIQUE INDEX hr_payroll_runs_pkey ON public.hr_payroll_runs USING btree (id);
CREATE UNIQUE INDEX hr_payslips_payroll_run_id_user_id_key ON public.hr_payslips USING btree (payroll_run_id, user_id);
CREATE UNIQUE INDEX hr_payslips_pkey ON public.hr_payslips USING btree (id);
CREATE INDEX hr_payslips_user_idx ON public.hr_payslips USING btree (user_id, created_at DESC);
CREATE INDEX idx_hr_payslips_payroll_run_id ON public.hr_payslips USING btree (payroll_run_id);
CREATE UNIQUE INDEX hr_probation_reviews_pkey ON public.hr_probation_reviews USING btree (id);
CREATE INDEX hr_probation_reviews_status_idx ON public.hr_probation_reviews USING btree (status);
CREATE INDEX hr_probation_reviews_user_idx ON public.hr_probation_reviews USING btree (user_id);
CREATE INDEX idx_hr_probation_reviews_approved_by ON public.hr_probation_reviews USING btree (approved_by);
CREATE INDEX idx_hr_probation_reviews_reviewer_id ON public.hr_probation_reviews USING btree (reviewer_id);
CREATE INDEX idx_hr_probation_reviews_user_id ON public.hr_probation_reviews USING btree (user_id);
CREATE UNIQUE INDEX hr_public_holidays_date_name_key ON public.hr_public_holidays USING btree (date, name);
CREATE UNIQUE INDEX hr_public_holidays_pkey ON public.hr_public_holidays USING btree (id);
CREATE INDEX idx_hr_ph_date ON public.hr_public_holidays USING btree (date);
CREATE UNIQUE INDEX hr_push_tokens_pkey ON public.hr_push_tokens USING btree (id);
CREATE UNIQUE INDEX hr_push_tokens_token_key ON public.hr_push_tokens USING btree (token);
CREATE INDEX hr_push_tokens_user_active_idx ON public.hr_push_tokens USING btree (user_id) WHERE (is_active = true);
CREATE INDEX hr_review_penalty_attributed_idx ON public.hr_review_penalty USING gin (attributed_user_ids);
CREATE UNIQUE INDEX hr_review_penalty_gbp_review_id_key ON public.hr_review_penalty USING btree (gbp_review_id);
CREATE INDEX hr_review_penalty_outlet_date_idx ON public.hr_review_penalty USING btree (outlet_id, review_date);
CREATE UNIQUE INDEX hr_review_penalty_pkey ON public.hr_review_penalty USING btree (id);
CREATE INDEX hr_review_penalty_status_idx ON public.hr_review_penalty USING btree (status, created_at);
CREATE UNIQUE INDEX hr_salary_history_pkey ON public.hr_salary_history USING btree (id);
CREATE INDEX idx_hr_salary_history_user ON public.hr_salary_history USING btree (user_id, effective_date DESC);
CREATE UNIQUE INDEX hr_schedule_shifts_pkey ON public.hr_schedule_shifts USING btree (id);
CREATE INDEX idx_hr_schedule_shifts_schedule_id ON public.hr_schedule_shifts USING btree (schedule_id);
CREATE INDEX idx_hr_shifts_schedule ON public.hr_schedule_shifts USING btree (schedule_id);
CREATE INDEX idx_hr_shifts_user ON public.hr_schedule_shifts USING btree (user_id, shift_date);
CREATE UNIQUE INDEX hr_schedules_outlet_id_week_start_key ON public.hr_schedules USING btree (outlet_id, week_start);
CREATE UNIQUE INDEX hr_schedules_pkey ON public.hr_schedules USING btree (id);
CREATE UNIQUE INDEX hr_shift_swap_requests_pkey ON public.hr_shift_swap_requests USING btree (id);
CREATE INDEX idx_hr_shift_swap_requests_requester_shift_id ON public.hr_shift_swap_requests USING btree (requester_shift_id);
CREATE INDEX idx_hr_shift_swap_requests_target_shift_id ON public.hr_shift_swap_requests USING btree (target_shift_id);
CREATE INDEX idx_hr_swap_requester ON public.hr_shift_swap_requests USING btree (requester_id, status);
CREATE INDEX idx_hr_swap_target ON public.hr_shift_swap_requests USING btree (target_id, status);
CREATE UNIQUE INDEX hr_shift_templates_pkey ON public.hr_shift_templates USING btree (id);
CREATE INDEX idx_hr_st_outlet ON public.hr_shift_templates USING btree (outlet_id, is_active);
CREATE UNIQUE INDEX hr_staff_availability_pkey ON public.hr_staff_availability USING btree (id);
CREATE UNIQUE INDEX hr_staff_availability_user_id_date_key ON public.hr_staff_availability USING btree (user_id, date);
CREATE INDEX idx_hr_avail_user ON public.hr_staff_availability USING btree (user_id, date);
CREATE UNIQUE INDEX hr_staff_weekly_availability_pkey ON public.hr_staff_weekly_availability USING btree (id);
CREATE INDEX hr_staff_weekly_availability_user_day_idx ON public.hr_staff_weekly_availability USING btree (user_id, day_of_week);
CREATE UNIQUE INDEX hr_stat_eis_config_pkey ON public.hr_stat_eis_config USING btree (id);
CREATE UNIQUE INDEX hr_stat_epf_rates_pkey ON public.hr_stat_epf_rates USING btree (id);
CREATE UNIQUE INDEX hr_stat_hrdf_config_pkey ON public.hr_stat_hrdf_config USING btree (id);
CREATE UNIQUE INDEX hr_stat_pcb_brackets_pkey ON public.hr_stat_pcb_brackets USING btree (id);
CREATE UNIQUE INDEX hr_stat_pcb_reliefs_pkey ON public.hr_stat_pcb_reliefs USING btree (id);
CREATE UNIQUE INDEX hr_stat_socso_config_pkey ON public.hr_stat_socso_config USING btree (id);
CREATE UNIQUE INDEX hr_tax_relief_catalog_code_key ON public.hr_tax_relief_catalog USING btree (code);
CREATE UNIQUE INDEX hr_tax_relief_catalog_pkey ON public.hr_tax_relief_catalog USING btree (id);
CREATE UNIQUE INDEX indeed_ads_invoice_invoice_number_key ON public.indeed_ads_invoice USING btree (invoice_number);
CREATE INDEX indeed_ads_invoice_issue_date_idx ON public.indeed_ads_invoice USING btree (issue_date DESC);
CREATE UNIQUE INDEX indeed_ads_invoice_pkey ON public.indeed_ads_invoice USING btree (id);
CREATE INDEX indeed_ads_invoice_status_idx ON public.indeed_ads_invoice USING btree (status);
CREATE INDEX idx_indeed_ads_job_outlet_id ON public.indeed_ads_job USING btree (outlet_id);
CREATE INDEX indeed_ads_job_campaign_idx ON public.indeed_ads_job USING btree (campaign_id);
CREATE INDEX indeed_ads_job_city_idx ON public.indeed_ads_job USING btree (location_city);
CREATE UNIQUE INDEX indeed_ads_job_indeed_job_id_key ON public.indeed_ads_job USING btree (indeed_job_id);
CREATE INDEX indeed_ads_job_outlet_idx ON public.indeed_ads_job USING btree (outlet_id);
CREATE UNIQUE INDEX indeed_ads_job_pkey ON public.indeed_ads_job USING btree (id);
CREATE INDEX idx_indeed_ads_metric_daily_job_id ON public.indeed_ads_metric_daily USING btree (job_id);
CREATE INDEX indeed_ads_metric_daily_date_idx ON public.indeed_ads_metric_daily USING btree (date DESC);
CREATE UNIQUE INDEX indeed_ads_metric_daily_date_job_id_key ON public.indeed_ads_metric_daily USING btree (date, job_id);
CREATE INDEX indeed_ads_metric_daily_job_date_idx ON public.indeed_ads_metric_daily USING btree (job_id, date DESC);
CREATE UNIQUE INDEX indeed_ads_metric_daily_pkey ON public.indeed_ads_metric_daily USING btree (id);
CREATE UNIQUE INDEX indeed_ads_sync_log_pkey ON public.indeed_ads_sync_log USING btree (id);
CREATE INDEX indeed_ads_sync_log_started_idx ON public.indeed_ads_sync_log USING btree (started_at DESC);
CREATE INDEX idx_issued_rewards_brand_status ON public.issued_rewards USING btree (brand_id, status);
CREATE INDEX idx_issued_rewards_member ON public.issued_rewards USING btree (member_id);
CREATE INDEX idx_issued_rewards_redeemed_at ON public.issued_rewards USING btree (redeemed_at) WHERE (redeemed_at IS NOT NULL);
CREATE INDEX idx_issued_rewards_template ON public.issued_rewards USING btree (voucher_template_id);
CREATE UNIQUE INDEX issued_rewards_code_key ON public.issued_rewards USING btree (code);
CREATE UNIQUE INDEX issued_rewards_pkey ON public.issued_rewards USING btree (id);
CREATE UNIQUE INDEX jkk_daily_snapshots_pkey ON public.jkk_daily_snapshots USING btree (snapshot_date);
CREATE INDEX dashboard_stats_key_time_idx ON public.jkk_dashboard_stats USING btree (metric_key, measured_at DESC);
CREATE UNIQUE INDEX dashboard_stats_metric_key_measured_at_key ON public.jkk_dashboard_stats USING btree (metric_key, measured_at);
CREATE UNIQUE INDEX dashboard_stats_pkey ON public.jkk_dashboard_stats USING btree (id);
CREATE INDEX headlines_outlet_idx ON public.jkk_headlines USING btree (outlet);
CREATE UNIQUE INDEX headlines_pkey ON public.jkk_headlines USING btree (id);
CREATE INDEX headlines_published_at_idx ON public.jkk_headlines USING btree (published_at DESC);
CREATE UNIQUE INDEX jkk_headlines_outlet_title_key ON public.jkk_headlines USING btree (outlet, title);
CREATE INDEX jkk_internal_messages_group_time_idx ON public.jkk_internal_messages USING btree (group_label, message_at DESC);
CREATE UNIQUE INDEX jkk_internal_messages_pkey ON public.jkk_internal_messages USING btree (id);
CREATE INDEX jkk_internal_messages_sentiment_idx ON public.jkk_internal_messages USING btree (sentiment_label);
CREATE UNIQUE INDEX social_posts_pkey ON public.jkk_social_posts USING btree (id);
CREATE INDEX social_posts_platform_idx ON public.jkk_social_posts USING btree (platform);
CREATE UNIQUE INDEX social_posts_post_url_key ON public.jkk_social_posts USING btree (post_url);
CREATE INDEX social_posts_posted_at_idx ON public.jkk_social_posts USING btree (posted_at DESC);
CREATE INDEX idx_member_brands_brand ON public.member_brands USING btree (brand_id);
CREATE INDEX idx_member_brands_brand_id ON public.member_brands USING btree (brand_id);
CREATE INDEX idx_member_brands_brand_joined ON public.member_brands USING btree (brand_id, joined_at DESC);
CREATE INDEX idx_member_brands_brand_last_visit ON public.member_brands USING btree (brand_id, last_visit_at);
CREATE INDEX idx_member_brands_brand_top_spent ON public.member_brands USING btree (brand_id, total_spent DESC);
CREATE INDEX idx_member_brands_current_tier_id ON public.member_brands USING btree (current_tier_id);
CREATE INDEX idx_member_brands_member ON public.member_brands USING btree (member_id);
CREATE INDEX idx_member_brands_member_id ON public.member_brands USING btree (member_id);
CREATE INDEX idx_member_brands_tier ON public.member_brands USING btree (current_tier_id);
CREATE UNIQUE INDEX member_brands_member_id_brand_id_key ON public.member_brands USING btree (member_id, brand_id);
CREATE UNIQUE INDEX member_brands_pkey ON public.member_brands USING btree (id);
CREATE UNIQUE INDEX member_notification_prefs_pkey ON public.member_notification_prefs USING btree (member_id);
CREATE INDEX idx_members_phone ON public.members USING btree (phone);
CREATE UNIQUE INDEX members_phone_key ON public.members USING btree (phone);
CREATE UNIQUE INDEX members_pkey ON public.members USING btree (id);
CREATE INDEX members_sms_opt_out_idx ON public.members USING btree (sms_opt_out) WHERE (sms_opt_out = true);
CREATE INDEX idx_mission_assignments_active_week ON public.mission_assignments USING btree (member_id, week_start_at) WHERE (status = 'active'::text);
CREATE INDEX idx_mission_assignments_member ON public.mission_assignments USING btree (member_id, status);
CREATE INDEX idx_mission_assignments_mission_id ON public.mission_assignments USING btree (mission_id);
CREATE INDEX idx_mission_assignments_week ON public.mission_assignments USING btree (week_start_at);
CREATE UNIQUE INDEX mission_assignments_member_week_mission_key ON public.mission_assignments USING btree (member_id, week_start_at, mission_id);
CREATE UNIQUE INDEX mission_assignments_pkey ON public.mission_assignments USING btree (id);
CREATE INDEX idx_mission_swap_history_assignment_id ON public.mission_swap_history USING btree (assignment_id);
CREATE INDEX idx_mission_swap_history_from_mission_id ON public.mission_swap_history USING btree (from_mission_id);
CREATE INDEX idx_mission_swap_history_to_mission_id ON public.mission_swap_history USING btree (to_mission_id);
CREATE INDEX ix_mission_swap_history_assignment ON public.mission_swap_history USING btree (assignment_id);
CREATE INDEX ix_mission_swap_history_member_week ON public.mission_swap_history USING btree (member_id, week_start_at DESC);
CREATE UNIQUE INDEX mission_swap_history_pkey ON public.mission_swap_history USING btree (id);
CREATE UNIQUE INDEX ux_mission_swap_one_per_member_per_week ON public.mission_swap_history USING btree (member_id, week_start_at);
CREATE INDEX music_alerts_device_opened ON public.music_alerts USING btree (device_id, opened_at DESC);
CREATE UNIQUE INDEX music_alerts_one_open ON public.music_alerts USING btree (device_id, type) WHERE (resolved_at IS NULL);
CREATE INDEX music_alerts_outlet_open ON public.music_alerts USING btree (outlet_id) WHERE (resolved_at IS NULL);
CREATE UNIQUE INDEX music_alerts_pkey ON public.music_alerts USING btree (id);
CREATE UNIQUE INDEX music_devices_device_fingerprint_key ON public.music_devices USING btree (device_fingerprint);
CREATE INDEX music_devices_outlet ON public.music_devices USING btree (outlet_id);
CREATE UNIQUE INDEX music_devices_pkey ON public.music_devices USING btree (id);
CREATE UNIQUE INDEX music_heartbeats_device_reported ON public.music_heartbeats USING btree (device_id, reported_at);
CREATE INDEX music_heartbeats_outlet_reported ON public.music_heartbeats USING btree (outlet_id, reported_at DESC);
CREATE UNIQUE INDEX music_heartbeats_pkey ON public.music_heartbeats USING btree (id);
CREATE UNIQUE INDEX music_playlist_tracks_pkey ON public.music_playlist_tracks USING btree (id);
CREATE INDEX music_playlist_tracks_playlist ON public.music_playlist_tracks USING btree (playlist_id);
CREATE UNIQUE INDEX music_playlist_tracks_pos ON public.music_playlist_tracks USING btree (playlist_id, "position");
CREATE UNIQUE INDEX music_playlists_pkey ON public.music_playlists USING btree (id);
CREATE INDEX music_schedules_outlet ON public.music_schedules USING btree (outlet_id) WHERE active;
CREATE UNIQUE INDEX music_schedules_pkey ON public.music_schedules USING btree (id);
CREATE UNIQUE INDEX music_tracks_pkey ON public.music_tracks USING btree (id);
CREATE INDEX idx_mystery_drops_member ON public.mystery_drops USING btree (member_id);
CREATE INDEX idx_mystery_drops_order ON public.mystery_drops USING btree (order_id);
CREATE UNIQUE INDEX mystery_drops_pkey ON public.mystery_drops USING btree (id);
CREATE UNIQUE INDEX uq_mystery_drops_order ON public.mystery_drops USING btree (order_id) WHERE (order_id IS NOT NULL);
CREATE INDEX idx_mystery_pool_brand_active ON public.mystery_pool USING btree (brand_id, is_active);
CREATE UNIQUE INDEX mystery_pool_pkey ON public.mystery_pool USING btree (id);
CREATE INDEX notification_campaigns_enabled_idx ON public.notification_campaigns USING btree (enabled) WHERE (enabled = true);
CREATE UNIQUE INDEX notification_campaigns_key_key ON public.notification_campaigns USING btree (key);
CREATE INDEX notification_campaigns_kind_enabled_idx ON public.notification_campaigns USING btree (trigger_kind, enabled) WHERE (enabled = true);
CREATE UNIQUE INDEX notification_campaigns_pkey ON public.notification_campaigns USING btree (id);
CREATE INDEX idx_notification_sends_campaign_id ON public.notification_sends USING btree (campaign_id);
CREATE INDEX notification_sends_campaign_member_sent_idx ON public.notification_sends USING btree (campaign_id, member_id, sent_at DESC);
CREATE INDEX notification_sends_campaign_sent_idx ON public.notification_sends USING btree (campaign_id, sent_at DESC);
CREATE INDEX notification_sends_member_attribution_idx ON public.notification_sends USING btree (member_id, sent_at DESC) WHERE (attributed_order_id IS NULL);
CREATE UNIQUE INDEX notification_sends_pkey ON public.notification_sends USING btree (id);
CREATE INDEX idx_order_items_order ON public.order_items USING btree (order_id);
CREATE UNIQUE INDEX order_items_pkey ON public.order_items USING btree (id);
CREATE INDEX idx_orders_created_at ON public.orders USING btree (created_at DESC);
CREATE INDEX idx_orders_customer_phone ON public.orders USING btree (customer_phone) WHERE (customer_phone IS NOT NULL);
CREATE INDEX idx_orders_status_created ON public.orders USING btree (status, created_at DESC);
CREATE INDEX idx_orders_store_status ON public.orders USING btree (store_id, status);
CREATE INDEX idx_orders_wallet_voucher_id ON public.orders USING btree (wallet_voucher_id) WHERE (wallet_voucher_id IS NOT NULL);
CREATE UNIQUE INDEX orders_order_number_key ON public.orders USING btree (order_number);
CREATE INDEX orders_payment_checkout_id_idx ON public.orders USING btree (payment_checkout_id) WHERE (payment_checkout_id IS NOT NULL);
CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);
CREATE INDEX orders_unprinted_idx ON public.orders USING btree (store_id, kitchen_docket_printed_at, status) WHERE (kitchen_docket_printed_at IS NULL);
CREATE INDEX idx_otp_codes_phone ON public.otp_codes USING btree (phone);
CREATE UNIQUE INDEX otp_codes_pkey ON public.otp_codes USING btree (id);
CREATE INDEX outlet_product_availability_outlet_unavailable ON public.outlet_product_availability USING btree (outlet_id) WHERE (NOT is_available);
CREATE UNIQUE INDEX outlet_product_availability_pkey ON public.outlet_product_availability USING btree (outlet_id, product_id);
CREATE INDEX outlet_product_availability_updated ON public.outlet_product_availability USING btree (outlet_id, updated_at DESC);
CREATE UNIQUE INDEX payment_gateway_config_pkey ON public.payment_gateway_config USING btree (method_id);
CREATE INDEX idx_point_transactions_brand_id ON public.point_transactions USING btree (brand_id);
CREATE INDEX idx_point_transactions_member ON public.point_transactions USING btree (member_id);
CREATE INDEX idx_point_transactions_member_id ON public.point_transactions USING btree (member_id);
CREATE INDEX idx_point_txn_brand_type_created ON public.point_transactions USING btree (brand_id, type, created_at);
CREATE INDEX idx_point_txn_member_brand_created ON public.point_transactions USING btree (member_id, brand_id, created_at DESC);
CREATE INDEX idx_point_txn_outlet ON public.point_transactions USING btree (outlet_id);
CREATE UNIQUE INDEX point_transactions_pkey ON public.point_transactions USING btree (id);
CREATE UNIQUE INDEX uq_point_transactions_earn_ref ON public.point_transactions USING btree (reference_id) WHERE ((type = 'earn'::text) AND (reference_id IS NOT NULL));
CREATE UNIQUE INDEX pos_branch_settings_pkey ON public.pos_branch_settings USING btree (outlet_id);
CREATE UNIQUE INDEX pos_kitchen_stations_pkey ON public.pos_kitchen_stations USING btree (id);
CREATE INDEX idx_pos_order_items_kitchen ON public.pos_order_items USING btree (kitchen_station, kitchen_status);
CREATE INDEX idx_pos_order_items_order ON public.pos_order_items USING btree (order_id);
CREATE UNIQUE INDEX pos_order_items_pkey ON public.pos_order_items USING btree (id);
CREATE INDEX idx_pos_payments_order ON public.pos_order_payments USING btree (order_id);
CREATE UNIQUE INDEX pos_order_payments_pkey ON public.pos_order_payments USING btree (id);
CREATE INDEX idx_pos_orders_created ON public.pos_orders USING btree (created_at DESC);
CREATE INDEX idx_pos_orders_customer_phone ON public.pos_orders USING btree (customer_phone) WHERE (customer_phone IS NOT NULL);
CREATE INDEX idx_pos_orders_outlet ON public.pos_orders USING btree (outlet_id, status);
CREATE INDEX idx_pos_orders_shift ON public.pos_orders USING btree (shift_id);
CREATE UNIQUE INDEX pos_orders_external_id_uniq ON public.pos_orders USING btree (external_id) WHERE (external_id IS NOT NULL);
CREATE INDEX pos_orders_grab_unprinted_idx ON public.pos_orders USING btree (outlet_id, created_at) WHERE ((source = 'grabfood'::text) AND (kitchen_docket_printed_at IS NULL));
CREATE UNIQUE INDEX pos_orders_order_number_key ON public.pos_orders USING btree (order_number);
CREATE UNIQUE INDEX pos_orders_pkey ON public.pos_orders USING btree (id);
CREATE INDEX pos_orders_refund_of_idx ON public.pos_orders USING btree (refund_of_order_id) WHERE (refund_of_order_id IS NOT NULL);
CREATE INDEX idx_pos_pair_events_created ON public.pos_pair_events USING btree (created_at);
CREATE INDEX idx_pos_pair_events_outlet ON public.pos_pair_events USING btree (outlet_id, created_at);
CREATE UNIQUE INDEX pos_pair_events_pkey ON public.pos_pair_events USING btree (id);
CREATE INDEX idx_pos_printer_config_outlet ON public.pos_printer_config USING btree (outlet_id);
CREATE UNIQUE INDEX pos_printer_config_pkey ON public.pos_printer_config USING btree (id);
CREATE UNIQUE INDEX pos_promotions_pkey ON public.pos_promotions USING btree (id);
CREATE INDEX idx_pos_layouts_outlet ON public.pos_register_layouts USING btree (outlet_id, sort_order);
CREATE UNIQUE INDEX pos_register_layouts_pkey ON public.pos_register_layouts USING btree (id);
CREATE UNIQUE INDEX pos_registers_pkey ON public.pos_registers USING btree (id);
CREATE INDEX idx_pos_shifts_outlet ON public.pos_shifts USING btree (outlet_id, opened_at DESC);
CREATE UNIQUE INDEX pos_shifts_pkey ON public.pos_shifts USING btree (id);
CREATE UNIQUE INDEX product_co_purchase_scores_pk ON public.product_co_purchase_scores USING btree (product_id, paired_with);
CREATE INDEX idx_copurchase_seed_pid ON public.product_co_purchase_seed USING btree (product_id);
CREATE UNIQUE INDEX product_overrides_pkey ON public.product_overrides USING btree (product_id, store_id);
CREATE INDEX idx_round_seed ON public.product_round_seed USING btree (round, product_id);
CREATE INDEX idx_products_brand_category ON public.products USING btree (brand_id, category);
CREATE INDEX idx_products_brand_category_position ON public.products USING btree (brand_id, category, "position");
CREATE INDEX idx_products_brand_featured_position ON public.products USING btree (brand_id, is_featured, featured_position) WHERE (is_featured = true);
CREATE INDEX idx_products_online ON public.products USING gin (online_channels);
CREATE INDEX idx_products_storehub_id ON public.products USING btree (storehub_product_id);
CREATE INDEX idx_products_tags ON public.products USING gin (tags);
CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);
CREATE UNIQUE INDEX products_storehub_product_id_key ON public.products USING btree (storehub_product_id);
CREATE INDEX idx_pa_member ON public.promotion_applications USING btree (member_id, applied_at DESC);
CREATE INDEX idx_pa_promo ON public.promotion_applications USING btree (promotion_id, applied_at DESC);
CREATE INDEX idx_pa_ref ON public.promotion_applications USING btree (brand_id, reference_id);
CREATE INDEX idx_promotion_applications_brand_id ON public.promotion_applications USING btree (brand_id);
CREATE INDEX idx_promotion_applications_member_id ON public.promotion_applications USING btree (member_id);
CREATE INDEX idx_promotion_applications_promotion_id ON public.promotion_applications USING btree (promotion_id);
CREATE UNIQUE INDEX promotion_applications_pkey ON public.promotion_applications USING btree (id);
CREATE INDEX idx_promotions_brand_active ON public.promotions USING btree (brand_id, is_active);
CREATE INDEX idx_promotions_brand_id ON public.promotions USING btree (brand_id);
CREATE INDEX idx_promotions_code ON public.promotions USING btree (brand_id, promo_code) WHERE (promo_code IS NOT NULL);
CREATE INDEX idx_promotions_tier ON public.promotions USING btree (tier_id) WHERE (tier_id IS NOT NULL);
CREATE INDEX idx_promotions_tier_id ON public.promotions USING btree (tier_id);
CREATE UNIQUE INDEX promotions_brand_id_promo_code_key ON public.promotions USING btree (brand_id, promo_code);
CREATE INDEX promotions_combo_category_ids_gin ON public.promotions USING gin (combo_category_ids);
CREATE INDEX promotions_eligible_member_tags_gin ON public.promotions USING gin (eligible_member_tags);
CREATE UNIQUE INDEX promotions_pkey ON public.promotions USING btree (id);
CREATE INDEX idx_qa_alerts_app ON public.qa_alerts USING btree (app, alert_type);
CREATE INDEX idx_qa_alerts_created ON public.qa_alerts USING btree (created_at DESC);
CREATE INDEX idx_qa_alerts_unresolved ON public.qa_alerts USING btree (resolved_at) WHERE (resolved_at IS NULL);
CREATE UNIQUE INDEX qa_alerts_pkey ON public.qa_alerts USING btree (id);
CREATE INDEX idx_qa_fix_rules_enabled ON public.qa_fix_rules USING btree (enabled, priority DESC);
CREATE UNIQUE INDEX qa_fix_rules_pkey ON public.qa_fix_rules USING btree (id);
CREATE UNIQUE INDEX qa_health_checks_pkey ON public.qa_health_checks USING btree (id);
CREATE INDEX idx_rate_limits_key_created ON public.rate_limits USING btree (key, created_at DESC);
CREATE UNIQUE INDEX rate_limits_pkey ON public.rate_limits USING btree (id);
CREATE INDEX idx_redemptions_brand_id ON public.redemptions USING btree (brand_id);
CREATE INDEX idx_redemptions_brand_member_status ON public.redemptions USING btree (brand_id, member_id, status);
CREATE INDEX idx_redemptions_code ON public.redemptions USING btree (code);
CREATE INDEX idx_redemptions_expires ON public.redemptions USING btree (expires_at) WHERE ((status = 'pending'::text) AND (expires_at IS NOT NULL));
CREATE INDEX idx_redemptions_member_id ON public.redemptions USING btree (member_id);
CREATE INDEX idx_redemptions_pickup ON public.redemptions USING btree (pickup_outlet_id, status) WHERE (redemption_type = ANY (ARRAY['pickup'::text, 'delivery'::text]));
CREATE INDEX idx_redemptions_reward_id ON public.redemptions USING btree (reward_id);
CREATE UNIQUE INDEX redemptions_code_key ON public.redemptions USING btree (code);
CREATE UNIQUE INDEX redemptions_pkey ON public.redemptions USING btree (id);
CREATE INDEX idx_referral_attr_referrer ON public.referral_attributions USING btree (referrer_id);
CREATE INDEX idx_referral_attributions_referee_voucher_id ON public.referral_attributions USING btree (referee_voucher_id);
CREATE INDEX idx_referral_attributions_referrer_voucher_id ON public.referral_attributions USING btree (referrer_voucher_id);
CREATE UNIQUE INDEX referral_attributions_pkey ON public.referral_attributions USING btree (id);
CREATE UNIQUE INDEX referral_attributions_referee_id_key ON public.referral_attributions USING btree (referee_id);
CREATE INDEX idx_referral_codes_brand ON public.referral_codes USING btree (brand_id);
CREATE UNIQUE INDEX referral_codes_code_key ON public.referral_codes USING btree (code);
CREATE UNIQUE INDEX referral_codes_pkey ON public.referral_codes USING btree (member_id);
CREATE UNIQUE INDEX reward_configs_pkey ON public.reward_configs USING btree (reward_id);
CREATE UNIQUE INDEX reward_kinds_pkey ON public.reward_kinds USING btree (id);
CREATE INDEX idx_reward_missions_brand_active ON public.reward_missions USING btree (brand_id, is_active);
CREATE UNIQUE INDEX reward_missions_pkey ON public.reward_missions USING btree (id);
CREATE INDEX idx_rewards_brand_id ON public.rewards USING btree (brand_id);
CREATE INDEX idx_rewards_distribution_methods ON public.rewards USING gin (distribution_methods);
CREATE INDEX idx_rewards_fulfillment ON public.rewards USING gin (fulfillment_type);
CREATE INDEX idx_rewards_linked_promo ON public.rewards USING btree (linked_promotion_id) WHERE (linked_promotion_id IS NOT NULL);
CREATE INDEX idx_rewards_linked_promotion_id ON public.rewards USING btree (linked_promotion_id);
CREATE UNIQUE INDEX rewards_pkey ON public.rewards USING btree (id);
CREATE INDEX idx_sms_credits_brand ON public.sms_credits USING btree (brand_id);
CREATE UNIQUE INDEX sms_credits_pkey ON public.sms_credits USING btree (id);
CREATE INDEX idx_sms_logs_brand ON public.sms_logs USING btree (brand_id);
CREATE INDEX idx_sms_logs_brand_created ON public.sms_logs USING btree (brand_id, created_at DESC);
CREATE INDEX idx_sms_logs_campaign ON public.sms_logs USING btree (campaign_id);
CREATE INDEX idx_sms_logs_created ON public.sms_logs USING btree (created_at DESC);
CREATE UNIQUE INDEX sms_logs_pkey ON public.sms_logs USING btree (id);
CREATE INDEX idx_splash_posters_lookup ON public.splash_posters USING btree (brand_id, active, starts_at, ends_at);
CREATE INDEX idx_splash_posters_placement ON public.splash_posters USING btree (brand_id, placement, active);
CREATE INDEX idx_splash_posters_round ON public.splash_posters USING btree (brand_id, placement, active, round);
CREATE INDEX idx_splash_posters_sort_order ON public.splash_posters USING btree (placement, sort_order, updated_at DESC);
CREATE UNIQUE INDEX splash_posters_pkey ON public.splash_posters USING btree (id);
CREATE INDEX idx_staff_skill_coach_cache_user_id ON public.staff_skill_coach_cache USING btree (user_id);
CREATE UNIQUE INDEX staff_skill_coach_cache_pkey ON public.staff_skill_coach_cache USING btree (user_id);
CREATE UNIQUE INDEX storehub_products_pkey ON public.storehub_products USING btree (id);
CREATE INDEX idx_shsi_name ON public.storehub_sale_items USING btree (lower(name));
CREATE INDEX idx_shsi_outlet_time ON public.storehub_sale_items USING btree (outlet_id, transaction_time);
CREATE INDEX idx_shsi_product ON public.storehub_sale_items USING btree (storehub_product_id);
CREATE INDEX idx_shsi_sale ON public.storehub_sale_items USING btree (sale_id);
CREATE UNIQUE INDEX storehub_sale_items_pkey ON public.storehub_sale_items USING btree (id);
CREATE INDEX idx_storehub_sales_outlet_time ON public.storehub_sales USING btree (outlet_id, transaction_time);
CREATE INDEX idx_storehub_sales_time ON public.storehub_sales USING btree (transaction_time);
CREATE UNIQUE INDEX storehub_sales_pkey ON public.storehub_sales USING btree (id);
CREATE UNIQUE INDEX uq_storehub_sales_store_ref ON public.storehub_sales USING btree (storehub_store_id, ref_id);
CREATE INDEX idx_tbg_brand ON public.tier_benefit_grants USING btree (brand_id, granted_at DESC);
CREATE INDEX idx_tbg_member ON public.tier_benefit_grants USING btree (member_id, benefit_type);
CREATE INDEX idx_tier_benefit_grants_brand_id ON public.tier_benefit_grants USING btree (brand_id);
CREATE INDEX idx_tier_benefit_grants_issued_reward_id ON public.tier_benefit_grants USING btree (issued_reward_id);
CREATE INDEX idx_tier_benefit_grants_member_id ON public.tier_benefit_grants USING btree (member_id);
CREATE INDEX idx_tier_benefit_grants_tier_id ON public.tier_benefit_grants USING btree (tier_id);
CREATE UNIQUE INDEX tier_benefit_grants_member_id_benefit_type_period_key_key ON public.tier_benefit_grants USING btree (member_id, benefit_type, period_key);
CREATE UNIQUE INDEX tier_benefit_grants_pkey ON public.tier_benefit_grants USING btree (id);
CREATE INDEX idx_tiers_brand ON public.tiers USING btree (brand_id, sort_order);
CREATE INDEX idx_tiers_brand_id ON public.tiers USING btree (brand_id);
CREATE UNIQUE INDEX tiers_brand_id_slug_key ON public.tiers USING btree (brand_id, slug);
CREATE UNIQUE INDEX tiers_pkey ON public.tiers USING btree (id);
CREATE UNIQUE INDEX user_streaks_pkey ON public.user_streaks USING btree (member_id);
CREATE INDEX idx_voucher_templates_brand ON public.voucher_templates USING btree (brand_id, is_active);
CREATE INDEX idx_voucher_templates_reward_kind_id ON public.voucher_templates USING btree (reward_kind_id);
CREATE UNIQUE INDEX voucher_templates_pkey ON public.voucher_templates USING btree (id);
