"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ClipboardCheck, Loader2, CheckCircle2, Clock, AlertCircle } from "lucide-react";
import { useFetch } from "@/lib/use-fetch";

type ChecklistSummary = {
  id: string;
  date: string;
  shift: "OPENING" | "MIDDAY" | "CLOSING";
  status: "PENDING" | "IN_PROGRESS" | "COMPLETED";
  sop: { id: string; title: string; category: { name: string } };
  outlet: { id: string; code: string; name: string };
  assignedTo: { id: string; name: string } | null;
  completedBy: { id: string; name: string } | null;
  totalItems: number;
  completedItems: number;
  progress: number;
};

const SHIFT_LABELS: Record<string, string> = { OPENING: "Opening", MIDDAY: "Midday", CLOSING: "Closing" };

const STATUS_CONFIG: Record<string, { icon: typeof CheckCircle2; color: string; bg: string }> = {
  PENDING: { icon: Clock, color: "text-yellow-600", bg: "bg-yellow-100" },
  IN_PROGRESS: { icon: AlertCircle, color: "text-blue-600", bg: "bg-blue-100" },
  COMPLETED: { icon: CheckCircle2, color: "text-green-600", bg: "bg-green-100" },
};

export default function ChecklistsPage() {
  // The outlet the person is actually working today (clocked-in → rostered →
  // home). Covering staff and roving managers get the right list this way,
  // instead of being pinned to a fixed — or missing — home outlet.
  const { data: activeOutlet } = useFetch<{ outletId: string | null; outletName: string | null; source: string }>(
    "/api/checklists/active-outlet",
  );
  const outletId = activeOutlet?.outletId ?? null;
  const [generating, setGenerating] = useState(false);

  const today = new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Kuala_Lumpur" });

  // Everyone sees all checklists for that outlet (assigned + unassigned/claimable)
  const queryUrl = outletId
    ? `/api/checklists?date=${today}&outletId=${outletId}`
    : null;

  const { data: checklists, isLoading, mutate } = useFetch<ChecklistSummary[]>(queryUrl);

  // Auto-generate on first access if no checklists exist today
  const [autoGenerated, setAutoGenerated] = useState(false);
  useEffect(() => {
    if (checklists && checklists.length === 0 && outletId && !autoGenerated && !isLoading) {
      setAutoGenerated(true);
      setGenerating(true);
      fetch("/api/checklists/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ outletId, date: today }),
      }).then(() => { mutate(); setGenerating(false); })
        .catch(() => setGenerating(false));
    }
  }, [checklists, outletId, autoGenerated, isLoading, today, mutate]);

  const completedCount = checklists?.filter((c) => c.status === "COMPLETED").length ?? 0;
  const totalCount = checklists?.length ?? 0;

  // Group by shift
  const grouped = (checklists ?? []).reduce<Record<string, ChecklistSummary[]>>((acc, cl) => {
    if (!acc[cl.shift]) acc[cl.shift] = [];
    acc[cl.shift].push(cl);
    return acc;
  }, {});

  return (
    <div className="px-4 py-4">
      <div className="space-y-4">
        {/* Header */}
        <div>
          <h1 className="font-heading text-lg font-bold text-brand-dark">Checklists</h1>
          <p className="text-sm text-gray-500">{today}</p>
        </div>

        {/* Progress */}
        {checklists && checklists.length > 0 && (
          <div className="flex items-center gap-3">
            <div className="flex-1 rounded-full bg-gray-100 h-2 overflow-hidden">
              <div
                className="h-full bg-terracotta rounded-full transition-all"
                style={{ width: `${totalCount > 0 ? (completedCount / totalCount) * 100 : 0}%` }}
              />
            </div>
            <span className="text-xs font-medium text-gray-500">
              {completedCount}/{totalCount}
            </span>
          </div>
        )}

        {/* Loading (initial fetch or auto-generate in progress) */}
        {(isLoading || generating) && (
          <div className="flex justify-center py-8">
            <Loader2 className="h-6 w-6 animate-spin text-terracotta" />
          </div>
        )}

        {/* No working outlet resolved — the person isn't clocked in, rostered,
            or assigned a home outlet today, so there's nothing to show. */}
        {!isLoading && !generating && !outletId && (
          <Card className="px-4 py-8 text-center">
            <ClipboardCheck className="mx-auto h-10 w-10 text-gray-300" />
            <p className="mt-3 text-sm text-gray-500">No outlet for today</p>
            <p className="mt-1 text-xs text-gray-400">Clock in at your outlet to see its checklists</p>
          </Card>
        )}

        {/* Empty state — outlet resolved but no SOPs scheduled today */}
        {!isLoading && !generating && outletId && (!checklists || checklists.length === 0) && (
          <Card className="px-4 py-8 text-center">
            <ClipboardCheck className="mx-auto h-10 w-10 text-gray-300" />
            <p className="mt-3 text-sm text-gray-500">No checklists today</p>
            <p className="mt-1 text-xs text-gray-400">
              Nothing scheduled{activeOutlet?.outletName ? ` for ${activeOutlet.outletName}` : " for this outlet"}
            </p>
          </Card>
        )}

        {/* Checklists grouped by shift */}
        {["OPENING", "MIDDAY", "CLOSING"].map((shift) => {
          const items = grouped[shift];
          if (!items || items.length === 0) return null;
          return (
            <div key={shift}>
              <h2 className="mb-2 text-xs font-semibold uppercase tracking-wider text-gray-400">
                {SHIFT_LABELS[shift]} Shift
              </h2>
              <div className="space-y-2">
                {items.map((cl) => {
                  const config = STATUS_CONFIG[cl.status];
                  const Icon = config.icon;
                  return (
                    <Link key={cl.id} href={`/checklists/${cl.id}`}>
                      <Card className="px-3 py-2.5 transition-all active:bg-gray-50">
                        <div className="flex items-center gap-3">
                          <div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${config.bg}`}>
                            <Icon className={`h-4 w-4 ${config.color}`} />
                          </div>
                          <div className="flex-1 min-w-0">
                            <p className="text-sm font-medium text-gray-900 truncate">{cl.sop.title}</p>
                            <p className="text-[10px] text-gray-400">
                              {cl.sop.category.name} · {cl.completedItems}/{cl.totalItems} items
                              {cl.assignedTo ? ` · ${cl.assignedTo.name}` : " · Anyone"}
                            </p>
                          </div>
                          <div className="shrink-0 text-right">
                            <p className="text-sm font-bold text-gray-700">{cl.progress}%</p>
                          </div>
                        </div>
                        {/* Mini progress bar */}
                        <div className="mt-2 rounded-full bg-gray-100 h-1 overflow-hidden">
                          <div
                            className={`h-full rounded-full transition-all ${cl.status === "COMPLETED" ? "bg-green-500" : "bg-terracotta"}`}
                            style={{ width: `${cl.progress}%` }}
                          />
                        </div>
                      </Card>
                    </Link>
                  );
                })}
              </div>
            </div>
          );
        })}

        {/* History link */}
        {checklists && checklists.length > 0 && (
          <Link href="/checklists/history" className="block text-center text-xs text-terracotta py-2">
            View history →
          </Link>
        )}
      </div>
    </div>
  );
}
