import { useCallback, useState } from "react";
import {
  ActivityIndicator,
  FlatList,
  Pressable,
  RefreshControl,
  Text,
  View,
} from "react-native";
import { useFocusEffect, useRouter } from "expo-router";
import { Screen } from "../../../components/Screen";
import { PageHeader } from "../../../components/PageHeader";
import {
  AlertCircle,
  CheckCircle2,
  ChevronRight,
  ClipboardCheck,
  Clock,
} from "lucide-react-native";
import { useStaff } from "../../../lib/store";
import {
  generateChecklists,
  listChecklists,
  type ChecklistShift,
  type ChecklistSummary,
} from "../../../lib/ops/checklists";

const SHIFT_LABEL: Record<ChecklistShift, string> = {
  OPENING: "Opening",
  MIDDAY: "Midday",
  CLOSING: "Closing",
};

const SHIFT_ORDER: ChecklistShift[] = ["OPENING", "MIDDAY", "CLOSING"];

export default function ChecklistsList() {
  const router = useRouter();
  const session = useStaff((s) => s.session);
  const [items, setItems] = useState<ChecklistSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [scope, setScope] = useState<"mine" | "all">("mine");

  const today = todayString();

  const load = useCallback(
    async (silent = false) => {
      if (!session?.outletId) {
        setItems([]);
        setLoading(false);
        return;
      }
      if (!silent) setLoading(true);
      setError(null);
      try {
        const data = await listChecklists({
          date: today,
          outletId: session.outletId,
        });
        if (data.length === 0 && !autoGenerated) {
          setAutoGenerated(true);
          try {
            await generateChecklists({
              outletId: session.outletId,
              date: today,
            });
            const after = await listChecklists({
              date: today,
              outletId: session.outletId,
            });
            setItems(after);
          } catch {
            setItems([]);
          }
        } else {
          setItems(data);
        }
      } catch (e) {
        setError(e instanceof Error ? e.message : "Couldn't load");
      } finally {
        setLoading(false);
        setRefreshing(false);
      }
    },
    [session?.outletId, today, autoGenerated],
  );

  useFocusEffect(
    useCallback(() => {
      load(true);
    }, [load]),
  );

  // "Mine" = shared whole-outlet tasks (opening/closing/cleaning, everyone's
  // job), checklists assigned to me, ones I've already ticked items on, or
  // unassigned ("Anyone") ones I can pick up; it hides only checklists assigned
  // to someone else that I haven't touched. Default view so staff land on their
  // own work, with an "All" toggle for the full outlet board.
  const myId = session?.userId ?? null;
  const isMine = (c: ChecklistSummary) =>
    c.shared ||
    !c.assignedTo ||
    c.assignedTo.id === myId ||
    (c.myCompletedItems ?? 0) > 0;
  const mineCount = items.filter(isMine).length;
  const visible = scope === "all" ? items : items.filter(isMine);

  const grouped = SHIFT_ORDER.map((shift) => ({
    shift,
    items: visible.filter((c) => c.shift === shift),
  })).filter((g) => g.items.length > 0);

  const completed = items.filter((c) => c.status === "COMPLETED").length;
  const total = items.length;
  const pct = total > 0 ? Math.round((completed / total) * 100) : 0;

  // Personal contribution across every checklist today, sum of
  // items the calling user has marked done divided by the total
  // possible items across all checklists. Surfaces the "you did X
  // of Y" number staff care about (vs the team-level X/Y above).
  const myItems = items.reduce((s, c) => s + (c.myCompletedItems ?? 0), 0);
  const totalItemCount = items.reduce((s, c) => s + c.totalItems, 0);

  return (
    <Screen>
      <PageHeader title="Checklists" />
      {loading && items.length === 0 ? (
        <View className="flex-1 items-center justify-center">
          <ActivityIndicator color="#A2492C" />
        </View>
      ) : error ? (
        <View className="flex-1 items-center justify-center px-6">
          <Text className="text-sm text-danger text-center">{error}</Text>
        </View>
      ) : (
        <FlatList
          data={grouped}
          keyExtractor={(g) => g.shift}
          contentContainerClassName="pt-2 pb-24"
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={() => {
                setRefreshing(true);
                load(true);
              }}
              tintColor="#A2492C"
            />
          }
          ListHeaderComponent={
            <View>
              {/* Progress card, team progress on top (checklists
                  fully completed) + personal contribution below
                  (items the calling user has ticked off across every
                  checklist today). */}
              {total > 0 ? (
                <View className="mb-5 rounded-3xl border border-border bg-surface px-4 py-3.5">
                  <View className="flex-row items-center justify-between">
                    <Text className="text-xs font-body-semi text-muted uppercase tracking-wide">
                      {dateLabel()}
                    </Text>
                    <Text className="text-xs font-body-bold text-muted-fg">
                      Team {completed} / {total}
                    </Text>
                  </View>
                  <View className="mt-2 h-2 overflow-hidden rounded-full bg-primary-50">
                    <View
                      className={`h-full ${pct === 100 ? "bg-success" : "bg-primary"}`}
                      style={{ width: `${pct}%` }}
                    />
                  </View>
                  <View className="mt-3 flex-row items-center justify-between border-t border-border pt-3">
                    <Text className="text-xs font-body-semi text-muted uppercase tracking-wide">
                      Your contribution
                    </Text>
                    <Text className="text-sm font-body-bold text-primary tabular-nums">
                      {myItems} of {totalItemCount} items
                    </Text>
                  </View>
                </View>
              ) : null}
              {total > 0 ? (
                <View className="mb-4 flex-row rounded-full bg-primary-50 p-1">
                  <Pressable
                    onPress={() => setScope("mine")}
                    className={`flex-1 items-center rounded-full py-2 ${
                      scope === "mine" ? "bg-surface" : ""
                    }`}
                  >
                    <Text
                      className={`text-xs font-body-semi ${
                        scope === "mine" ? "text-espresso" : "text-muted"
                      }`}
                    >
                      Mine ({mineCount})
                    </Text>
                  </Pressable>
                  <Pressable
                    onPress={() => setScope("all")}
                    className={`flex-1 items-center rounded-full py-2 ${
                      scope === "all" ? "bg-surface" : ""
                    }`}
                  >
                    <Text
                      className={`text-xs font-body-semi ${
                        scope === "all" ? "text-espresso" : "text-muted"
                      }`}
                    >
                      All ({total})
                    </Text>
                  </Pressable>
                </View>
              ) : null}
            </View>
          }
          ListEmptyComponent={
            <View className="mt-12 items-center px-6">
              <View className="h-20 w-20 items-center justify-center rounded-3xl bg-primary-50">
                <ClipboardCheck color="#A2492C" size={32} />
              </View>
              <Text className="mt-4 text-base font-display text-espresso">
                {total > 0 && scope === "mine"
                  ? "Nothing assigned to you"
                  : "No checklists today"}
              </Text>
              <Text className="mt-1 text-sm font-body text-muted-fg text-center">
                {total > 0 && scope === "mine"
                  ? "Tap All to see the team's checklists."
                  : "Nothing scheduled for this outlet."}
              </Text>
              {total > 0 && scope === "mine" ? (
                <Pressable
                  onPress={() => setScope("all")}
                  className="mt-4 rounded-full bg-primary px-5 py-2 active:opacity-80"
                >
                  <Text className="text-sm font-body-semi text-white">
                    Show all
                  </Text>
                </Pressable>
              ) : null}
            </View>
          }
          ItemSeparatorComponent={() => <View className="h-4" />}
          renderItem={({ item: group }) => (
            <View>
              <Text className="mb-2 text-[10px] font-body-bold uppercase tracking-wide text-muted">
                {SHIFT_LABEL[group.shift]} shift
              </Text>
              <View className="gap-2">
                {group.items.map((cl) => (
                  <ChecklistRow
                    key={cl.id}
                    cl={cl}
                    onPress={() => router.push(`/checklists/${cl.id}`)}
                  />
                ))}
              </View>
            </View>
          )}
      showsVerticalScrollIndicator={false}
    />
      )}
    </Screen>
  );
}

function ChecklistRow({
  cl,
  onPress,
}: {
  cl: ChecklistSummary;
  onPress: () => void;
}) {
  const Icon =
    cl.status === "COMPLETED"
      ? CheckCircle2
      : cl.status === "IN_PROGRESS"
        ? AlertCircle
        : Clock;
  const iconColor =
    cl.status === "COMPLETED"
      ? "#15803D"
      : cl.status === "IN_PROGRESS"
        ? "#2563EB"
        : "#F59E0B";
  const bg =
    cl.status === "COMPLETED"
      ? "bg-success/10"
      : cl.status === "IN_PROGRESS"
        ? "bg-blue-500/10"
        : "bg-amber-500/10";

  return (
    <Pressable
      onPress={onPress}
      className="rounded-2xl border border-border bg-surface px-3 py-2.5 active:bg-primary-50"
    >
      <View className="flex-row items-center gap-3">
        <View
          className={`h-9 w-9 items-center justify-center rounded-xl ${bg}`}
        >
          <Icon color={iconColor} size={16} />
        </View>
        <View className="flex-1">
          <Text
            className="text-base font-body-medium text-espresso"
            numberOfLines={1}
          >
            {cl.sop.title}
          </Text>
          <Text className="text-[10px] font-body text-muted">
            {cl.sop.category.name} · {cl.completedItems}/{cl.totalItems} items
            {cl.myCompletedItems > 0 ? ` · ${cl.myCompletedItems} by you` : ""}
            {cl.shared
              ? " · Shared"
              : cl.assignedTo
                ? ` · ${cl.assignedTo.name}`
                : " · Anyone"}
          </Text>
        </View>
        <View className="items-end">
          <Text className="text-base font-body-bold text-espresso">
            {cl.progress}%
          </Text>
        </View>
        <ChevronRight color="#D1D5DB" size={16} />
      </View>
      <View className="mt-2 h-1 overflow-hidden rounded-full bg-primary-50">
        <View
          className={`h-full ${cl.status === "COMPLETED" ? "bg-success" : "bg-primary"}`}
          style={{ width: `${cl.progress}%` }}
        />
      </View>
    </Pressable>
  );
}

function todayString(): string {
  const d = new Date(Date.now() + 8 * 60 * 60 * 1000);
  return d.toISOString().split("T")[0];
}

function dateLabel(): string {
  return new Date().toLocaleDateString([], {
    weekday: "long",
    day: "numeric",
    month: "short",
  });
}
