// ==========================================
// Demo data for development & preview
// Replace with Supabase queries in production
// ==========================================

import type {
  Brand,
  Outlet,
  Member,
  MemberBrand,
  Reward,
  PointTransaction,
  DashboardStats,
  Campaign,
  StaffUser,
} from "@/types";

export const demoBrands: Brand[] = [
  {
    id: "brand-celsius",
    name: "Celsius Coffee",
    slug: "celsius-coffee",
    logo_url: null,
    primary_color: "#1a1a1a",
    secondary_color: "#C2452D",
    points_per_rm: 1,
    currency: "MYR",
    is_active: true,
    points_expiry_months: 0,
    points_expiry_enabled: false,
    daily_earning_limit: 0,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-03-27T00:00:00Z",
  },
];

export const demoOutlets: Outlet[] = [
  {
    id: "outlet-sa",
    brand_id: "brand-celsius",
    name: "Shah Alam",
    address: "Section 7, Shah Alam",
    city: "Shah Alam",
    state: "Selangor",
    phone: "+60 3-5521 1234",
    storehub_store_id: "69662e56c164b700078242c9",
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "outlet-con",
    brand_id: "brand-celsius",
    name: "Conezion",
    address: "IOI Resort City, Putrajaya",
    city: "Putrajaya",
    state: "WP Putrajaya",
    phone: "+60 3-8920 5678",
    storehub_store_id: "6953b9226eb8b500070a79db",
    is_active: true,
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "outlet-tam",
    brand_id: "brand-celsius",
    name: "Tamarind Square",
    address: "Persiaran Multimedia, Cyberjaya",
    city: "Cyberjaya",
    state: "Selangor",
    phone: "+60 3-8322 9012",
    storehub_store_id: "68a8555979431c0007b493d2",
    is_active: true,
    created_at: "2026-02-01T00:00:00Z",
  },
];

export const demoMembers: Member[] = [
  {
    id: "member-1",
    phone: "+60123456789",
    name: "Ahmad Razak",
    email: "ahmad@email.com",
    birthday: "1990-05-15",
    preferred_outlet_id: "outlet-sa",
    created_at: "2026-01-10T00:00:00Z",
    updated_at: "2026-03-25T00:00:00Z",
  },
  {
    id: "member-2",
    phone: "+60198765432",
    name: "Siti Aminah",
    email: "siti@email.com",
    birthday: "1988-12-03",
    preferred_outlet_id: "outlet-con",
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-03-26T00:00:00Z",
  },
  {
    id: "member-3",
    phone: "+60171234567",
    name: "Lee Wei Ming",
    email: null,
    birthday: "1995-08-22",
    preferred_outlet_id: "outlet-tam",
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-03-27T00:00:00Z",
  },
  {
    id: "member-4",
    phone: "+60162345678",
    name: "Priya Nair",
    email: "priya@email.com",
    birthday: "1992-03-10",
    preferred_outlet_id: "outlet-sa",
    created_at: "2026-02-14T00:00:00Z",
    updated_at: "2026-03-20T00:00:00Z",
  },
  {
    id: "member-5",
    phone: "+60143456789",
    name: "Nurul Huda",
    email: "nurul@email.com",
    birthday: "1997-11-28",
    preferred_outlet_id: "outlet-con",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-27T00:00:00Z",
  },
];

export const demoMemberBrands: MemberBrand[] = [
  {
    id: "mb-1",
    member_id: "member-1",
    brand_id: "brand-celsius",
    points_balance: 750,
    total_points_earned: 1250,
    total_points_redeemed: 500,
    total_visits: 28,
    total_spent: 1250,
    joined_at: "2026-01-10T00:00:00Z",
    last_visit_at: "2026-03-25T14:30:00Z",
  },
  {
    id: "mb-2",
    member_id: "member-2",
    brand_id: "brand-celsius",
    points_balance: 1200,
    total_points_earned: 1800,
    total_points_redeemed: 600,
    total_visits: 35,
    total_spent: 1800,
    joined_at: "2026-01-15T00:00:00Z",
    last_visit_at: "2026-03-26T10:15:00Z",
  },
  {
    id: "mb-3",
    member_id: "member-3",
    brand_id: "brand-celsius",
    points_balance: 320,
    total_points_earned: 520,
    total_points_redeemed: 200,
    total_visits: 12,
    total_spent: 520,
    joined_at: "2026-02-01T00:00:00Z",
    last_visit_at: "2026-03-27T09:00:00Z",
  },
  {
    id: "mb-4",
    member_id: "member-4",
    brand_id: "brand-celsius",
    points_balance: 480,
    total_points_earned: 680,
    total_points_redeemed: 200,
    total_visits: 15,
    total_spent: 680,
    joined_at: "2026-02-14T00:00:00Z",
    last_visit_at: "2026-03-20T16:45:00Z",
  },
  {
    id: "mb-5",
    member_id: "member-5",
    brand_id: "brand-celsius",
    points_balance: 190,
    total_points_earned: 190,
    total_points_redeemed: 0,
    total_visits: 8,
    total_spent: 190,
    joined_at: "2026-03-01T00:00:00Z",
    last_visit_at: "2026-03-27T08:30:00Z",
  },
];

export const demoRewards: Reward[] = [
  {
    id: "reward-1",
    brand_id: "brand-celsius",
    name: "Free Americano",
    description: "Any size Americano (Hot or Iced)",
    image_url: null,
    points_required: 500,
    category: "drink",
    is_active: true,
    stock: null,
    max_redemptions_per_member: null,
    valid_from: null,
    valid_until: null,
    reward_type: "standard" as const,
    auto_issue: false,
    validity_days: null,
    discount_type: null,
    discount_value: null,
    max_discount_value: null,
    min_order_value: null,
    applicable_products: null,
    applicable_categories: null,
    free_product_ids: null,
    free_product_name: null,
    bogo_buy_qty: null,
    bogo_free_qty: null,
    fulfillment_type: null,
    expiry_minutes: null,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "reward-2",
    brand_id: "brand-celsius",
    name: "Free Latte",
    description: "Any size Latte (Hot or Iced)",
    image_url: null,
    points_required: 800,
    category: "drink",
    is_active: true,
    stock: null,
    max_redemptions_per_member: null,
    valid_from: null,
    valid_until: null,
    reward_type: "standard" as const,
    auto_issue: false,
    validity_days: null,
    discount_type: null,
    discount_value: null,
    max_discount_value: null,
    min_order_value: null,
    applicable_products: null,
    applicable_categories: null,
    free_product_ids: null,
    free_product_name: null,
    bogo_buy_qty: null,
    bogo_free_qty: null,
    fulfillment_type: null,
    expiry_minutes: null,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "reward-3",
    brand_id: "brand-celsius",
    name: "Free Coffee + Cake",
    description: "Any standard coffee + slice of cake",
    image_url: null,
    points_required: 1500,
    category: "food",
    is_active: true,
    stock: null,
    max_redemptions_per_member: null,
    valid_from: null,
    valid_until: null,
    reward_type: "standard" as const,
    auto_issue: false,
    validity_days: null,
    discount_type: null,
    discount_value: null,
    max_discount_value: null,
    min_order_value: null,
    applicable_products: null,
    applicable_categories: null,
    free_product_ids: null,
    free_product_name: null,
    bogo_buy_qty: null,
    bogo_free_qty: null,
    fulfillment_type: null,
    expiry_minutes: null,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "reward-4",
    brand_id: "brand-celsius",
    name: "20% Off Any Drink",
    description: "20% discount on any single drink",
    image_url: null,
    points_required: 300,
    category: "voucher",
    is_active: true,
    stock: null,
    max_redemptions_per_member: 3,
    valid_from: null,
    valid_until: null,
    reward_type: "standard" as const,
    auto_issue: false,
    validity_days: null,
    discount_type: null,
    discount_value: null,
    max_discount_value: null,
    min_order_value: null,
    applicable_products: null,
    applicable_categories: null,
    free_product_ids: null,
    free_product_name: null,
    bogo_buy_qty: null,
    bogo_free_qty: null,
    fulfillment_type: null,
    expiry_minutes: null,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "reward-5",
    brand_id: "brand-celsius",
    name: "Celsius Tumbler",
    description: "Exclusive branded stainless steel tumbler",
    image_url: null,
    points_required: 3000,
    category: "merch",
    is_active: true,
    stock: 50,
    max_redemptions_per_member: 1,
    valid_from: null,
    valid_until: null,
    reward_type: "standard" as const,
    auto_issue: false,
    validity_days: null,
    discount_type: null,
    discount_value: null,
    max_discount_value: null,
    min_order_value: null,
    applicable_products: null,
    applicable_categories: null,
    free_product_ids: null,
    free_product_name: null,
    bogo_buy_qty: null,
    bogo_free_qty: null,
    fulfillment_type: null,
    expiry_minutes: null,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const demoTransactions: PointTransaction[] = [
  {
    id: "txn-1",
    member_id: "member-1",
    brand_id: "brand-celsius",
    outlet_id: "outlet-sa",
    type: "earn",
    points: 25,
    balance_after: 750,
    description: "Purchase - Iced Latte + Croissant",
    reference_id: "POS-20260325-001",
    multiplier: 1,
    created_at: "2026-03-25T14:30:00Z",
    created_by: "staff-1",
  },
  {
    id: "txn-2",
    member_id: "member-2",
    brand_id: "brand-celsius",
    outlet_id: "outlet-con",
    type: "earn",
    points: 18,
    balance_after: 1200,
    description: "Purchase - Flat White",
    reference_id: "POS-20260326-042",
    multiplier: 1,
    created_at: "2026-03-26T10:15:00Z",
    created_by: "staff-2",
  },
  {
    id: "txn-3",
    member_id: "member-2",
    brand_id: "brand-celsius",
    outlet_id: "outlet-con",
    type: "redeem",
    points: -500,
    balance_after: 1182,
    description: "Redeemed: Free Americano",
    reference_id: "RDM-20260324-001",
    multiplier: 1,
    created_at: "2026-03-24T15:00:00Z",
    created_by: "staff-2",
  },
  {
    id: "txn-4",
    member_id: "member-5",
    brand_id: "brand-celsius",
    outlet_id: "outlet-con",
    type: "bonus",
    points: 50,
    balance_after: 190,
    description: "Welcome bonus - New member signup",
    reference_id: null,
    multiplier: 1,
    created_at: "2026-03-01T00:00:00Z",
    created_by: null,
  },
];

export const demoCampaigns: Campaign[] = [
  {
    id: "camp-1",
    brand_id: "brand-celsius",
    name: "Double Points Weekend",
    description: "Earn 2x points on all purchases every Saturday & Sunday",
    type: "multiplier",
    multiplier: 2,
    bonus_points: null,
    message: null,
    target_segment: "all",
    start_date: "2026-03-01T00:00:00Z",
    end_date: "2026-04-30T23:59:59Z",
    is_active: true,
    created_at: "2026-02-25T00:00:00Z",
  },
  {
    id: "camp-2",
    brand_id: "brand-celsius",
    name: "Welcome Bonus",
    description: "50 bonus points for all new member signups",
    type: "bonus",
    multiplier: null,
    bonus_points: 50,
    message: null,
    target_segment: "new",
    start_date: "2026-01-01T00:00:00Z",
    end_date: "2026-12-31T23:59:59Z",
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
  },
];

export const demoStaff: StaffUser[] = [
  {
    id: "staff-1",
    brand_id: "brand-celsius",
    outlet_id: "outlet-sa",
    outlet_ids: ["outlet-sa"],
    name: "Faizal Rahman",
    email: "faizal@celsius.my",
    role: "staff",
    pin_hash: "123456",
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "staff-2",
    brand_id: "brand-celsius",
    outlet_id: "outlet-con",
    outlet_ids: ["outlet-con"],
    name: "Aisha Noor",
    email: "aisha@celsius.my",
    role: "manager",
    pin_hash: "567890",
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "staff-3",
    brand_id: "brand-celsius",
    outlet_id: "outlet-tam",
    outlet_ids: ["outlet-tam"],
    name: "Hafiz Ismail",
    email: "hafiz@celsius.my",
    role: "staff",
    pin_hash: "901234",
    is_active: true,
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "staff-4",
    brand_id: "brand-celsius",
    outlet_id: "outlet-sa",
    outlet_ids: ["outlet-sa"],
    name: "Nur Aisyah",
    email: "aisyah@celsius.my",
    role: "staff",
    pin_hash: "345678",
    is_active: false,
    created_at: "2026-02-01T00:00:00Z",
  },
];

export const demoDashboardStats: DashboardStats = {
  total_members: 847,
  new_members_today: 12,
  new_members_this_month: 156,
  total_points_issued: 425000,
  total_points_redeemed: 187500,
  total_redemptions: 342,
  total_revenue_attributed: 425000,
  active_campaigns: 2,
  active_members_30d: 312,
  floating_points: 237500,
  member_transaction_pct: 68,
  avg_lifetime_value_members: 502,
  avg_lifetime_value_nonmembers: 0,
  reward_redemption_rate: 44,
  top_spenders: [],
  new_members_by_month: [],
  redemptions_by_month: [],
};
